---
title: "Conclusion on Politics and Trade Policy"
author: "Benjamin Heyries"
date: "Wednesday, January 28, 2015"
output: word_document
---

From the more detailed document, several conclusion can be drawn. First the TAA program constitutes a good example of the formation of the US trade policy. Indeed, it is seen as relevant by both the Administration and the Congress as having a real impact on the major issues, like the Depression,the War, the Cold War and the constitution of the "free-world" block, that appears during the studied period (1934-1958). Second, as it is a bipartisan program involving both executive and legislative branch of the political system, it reveals institutional organization that gravitate around the bill. As such, it represents the different tendencies present at that time. Finally, as the Trade Agreement Act (TAA) has to be extended at most every three years, the process of amendment and report of the program displays through time the actors and the arguments of the debate, providing a good picture of the opinions at that age.

##TAA frictions: 1934-1958 through the trade lens

* The domestic issue: it is historically the first that appears, as the bill is presented by the Roosevelt organization in order help recovery from the Great Depression. In opposition to this position, the protectionist movement insists in the danger that represent the TAA for local producer. This is where local private interest are defended: agriculture (multiple amendments), fur, oil (several times), watch, mining, fishing, wool and textile. The private interest amendment are usually provided by Representatives and Senators who are in direct contact with the concerned parties (South, especially for Democrats).

* The trade issue: the bill faces a specific opposition regarding the changes in the trade organization during the period. First, the TAA suffers from the expression of residual protectionist policies. The Smoot-Hawley agreement haunts the Congress until the late 1940s and the opposition to the status of most favored nation find a new application with the beginning of Cold War. Moreover, the birth of the GATT and the project of global organization challenges the content of the TAA. At multiple time, the TAA is linked to the GATT and the adoption a global organization charter (the ITO or the OTC). 

* Finally, the TAA is also a symbolic measure that deals with the establishment of a new world order. The TAA is first an emergency measure to counter the protectionist order, to preserve peace, then to win the war, to face the American responsibility of leading the economic world and finally to federate the liberal order to fight the Communist bloc. Several time, the argument was raised in order to preserve the bill that the US as the new leader have to send consistent messages to its allies and to the world. 

##The TAA: an institutional ballet

The TAA is also at the center of a complicated political game. Indeed, as it gives to the President more independence, it is fought by Congress by principle. As a consequence, when the Administration, usually in favor of the bill, suggest an extension, the Congress mobilize all its resources, through the House Way and Means Committee and the Senate Finance Committee, to reduce the application of it. On the contrary, the Administration brightly defends its prerogatives through the preservation of the Trade Agreement Committee in its role at the Tariffs Commission. Finally, the TAA enters in contradiction with some precedent legislation like the AAA, in the Section 22 which enables the President to arbitrarily raise the tariffs on agricultural product.

Besides the domestic fight around the TAA, the bill is compared and contrasted with the new international institution. As said before, the GATT and its several draft of prolongation cast a shadow on the adoption of the bill, and it has to be finally formally separated from it in 1951.

##Trade and ideology: the batlle for the TAA

Through the hearings, the debates, the amendments and the final vote, the TAA and its several extension represents fairly the different tendencies that were present in the Administration and in Congress during the pediod.

* During the first period, the "opportunists" dominate in both the Administration and in Congress. They succeeded to push the bill because of emergency situation, invoking recovery, peace and war. They are supported by the Free-traders from the Democrats like Cordell Hull, F. Sayre, H. Wallace, later on Clayton, Marshall and Acheson, and finally W. Thorpe, W. Brown and Senator Gore. The opportunist are particularly present in the Administration, Secretary Dulles and President Eisenhower representing the most striking examples. Opportunist builds free trade for exports and resolution of economic problems (the surplus of agricultural products during the 1930s, the excess of capital after the war, the dollar gap in the 1950s...).

* Against group, there are the harsh protectionist. They would like to get back to the Smoot-Hawley legislation. They are usually in the Republican ranks and are very strong in Congress, as they sometimes occupy important functions: Gearhart, chairman of the House Subcommittee on Tariffs and Foreign Trade leader of the challenge in 1948, Reed chairman of the House of Ways and Means Committee. These key people are completed by tenors like Simpson or Jenkins. They are supported by private interests, like Southern States Congressmen who are very tough on particular issues like oil, textile or agriculture. Finally the leaders of the Republican force in Congress in the persons of Miliken, at the head of the Senate Finance Committee and Vandenberg in the Senate, use these radical tendencies to moderate the ambitions of the first group.

At the end of the period, it seems like the forces at stake just balanced. Neither the free-traders nor the protectionist had a serious advantage and the disappearance of the security question as in support for free trade does not enable furthermore liberalization. The question is how the change in the question of security, as Cold War changes from the harsh period to the Detente, will change the tariff distribution. 