---
title: "Plan for the outcomes of tariff negotiations documents"
author: "Benjamin Heyries"
date: "Sunday, March 22, 2015"
output: html_document
---

In this document I list the countries that have reached to final phase of negotiation with the American delegation at the different round of the GATT. This achievement is indicated in the document by a letter from the chairman of the American delegation.

##Geneva I

  * Australia reached an agreement.The final list of tariff concession starts page 116
  * Benelux reached an agreement. The final list of tariff concessions start page 201.
  * Brazil reached an agreement. The final list of tariff concessions starts page 46.
  * Canada reached an agreement. The final list of tariffs concessions starts page 374.
  * Chile did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement. 
  * China did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Czechoslovakia did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Cuba did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Ceylon reached an agreement. The final list of tariff concessions starts page 9.
  * France reached an agreement. The final list of tariff concessions starts page 267.
  * The British Delegation reached an agreement. The final list of tariff concessions starts page 251.
  * India did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Lebanon and Syria did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Norway did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * New-Zealand reached an agreement. The final list of tariff concessions starts page 46.
  * Southern Rhodesia reached an agreement. The final list of tariff concessions starts page 10.
  * South Africa reached an agreement. The final list of tariff concessions starts page 32.

##Annecy

  * Sweden reached an agreement. The corrected final list of tariff concessions starts page 51. It is corrected by a second list at the end of the document.
  * El Salvador did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Peru did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Nicaragua reached an agreement. The final list of tariff concessions starts page 18.
  * Liberia did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Italy reached an agreement. The final list of tariff concessions starts page 72.
  * Haiti reached an agreement. The final list of tariff concessions starts page 45.
  * Greece reached an agreement. The final list of tariff concessions starts page 26.
  * Finland reached an agreement. The final list of tariff concessions starts page 41.
  * Uruguay reached an agreement. The final list of tariff concessions starts page 27.
  * Columbia did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Denmark reached an agreement. The final list of tariff concessions starts page 30.
  * Dominican Republic reached an agreement. The final list of tariff concessions starts page 52.
  
##Torquay

  * Dominican Republic reached an agreement. The final list of tariff concessions starts page 20.
  * France reached an agreement. The final list of tariff concessions starts page 47. 
  * Germany reached an agreement. The final list of tariff concessions starts page 104.
  * Guatemala did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Haiti did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Indonesia reached an agreement. The final list of tariff concessions starts page 19.
  * India did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Italy reached an agreement. The final list of tariff concessions starts page 37.
  * Korea reached an agreement. The final list of tariff concessions starts page 8.
  * Norway reached an agreement. The final list of tariff concessions starts page 27.
  * New-Zealand did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Peru reached an agreement. The final list of tariff concessions starts page 57.
  * South Africa did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Sweden reached an agreement. The final list of tariff concessions starts page 15.
  * Turkey reached an agreement. The final list of tariff concessions starts page 30.
  
##Geneva

  * Australia reached an agreement. The final list of tariff concessions starts page 8.
  * Austria reached an agreement. The final list of tariff concessions starts page 12.
  * Benelux reached an agreement. The final list of tariff concessions starts page 58.
  * Canada reached an agreement. The final list of tariff concessions starts page 28.
  * Chile reached an agreement. The final list of tariff concessions starts page 16.
  * Cuba reached an agreement. The final list of tariff concessions starts page 22.
  * Germany reached an agreement. The final list of tariff concessions starts page 94.
  * Denmark reached an agreement. The final list of tariff concessions starts page 17.
  * Dominican Republic reached an agreement. The final list of tariff concessions starts page 13.
  * ECSC reached an agreement. The final list of tariff concessions starts page 1. The concessions from the concessions are present in the particular document of each country member.
  * Finland reached an agreement. The final list of tariff concessions starts page 9.
  * France reached an agreement. The final list of tariff concessions starts page 25.
  * Greece did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Haiti reached an agreement. The final list of tariff concessions starts page 8.
  * India did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Italy reached an agreement. The final list of tariff concessions starts page 53.
  * Japan reached an agreement. The final list of tariff concessions starts page 37.
  * Nicaragua did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * Norway reached an agreement. The final list of tariff concessions starts page 11.
  * Peru reached an agreement. The final list of tariff concessions starts page 7.
  * Sweden reached an agreement. The final list of tariff concessions starts page 18.
  * Turkey reached an agreement. The final list of tariff concessions starts page 10.
  * South Africa did not reach an agreement. No notification of final agreement appears in the document, therefore the two contracting parties did not reach an agreement.
  * United Kingdom reached an agreement. The final list of tariff concessions starts page 47.

```{r}
Negotiations <- matrix(c("Australia", "Yes (116)", "No", "No", "Yes (8)", "Austria", "No", "No", "No", "Yes (12)", "Benelux", "Yes (201)", "No", "No", "Yes (58)", "Brazil", "Yes (46)", "No", "No", "No", "Canada", "Yes (374)", "No", "No", "Yes (28)", "Chile", "No", "No", "No", "Yes (16)", "China", "No", "No","No" , "No", "Columbia", "No", "No", "No", "No", "Cuba", "No", "No", "No", "Yes (22)", "Czechoslovakia", "No", "No", "No", "No", "Ceylon", "Yes (9)", "No", "No", "No", "Denmark", "No", "Yes (30)", "No", "Yes (17)", "Dominican Republic", "No", "Yes (52)", "Yes (20)",  "Yes (13)", "El Salvador", "No", "No", "No", "No", "ECSC", "No", "No", "No", "Yes (1)", "Finland", "No", "Yes (41)", "No", "Yes (9)", "France", "Yes (267)", "No", "Yes (47)", "Yes (25)", "Germany", "No", "No", "Yes (104)", "No","Guatemala", "No", "No", "No", "No", "Greece", "No", "Yes (26)", "No", "No", "Haiti", "No", "Yes (45)", "No", "Yes (8)", "India", "No", "No", "No" , "No", "Indonesia", "No", "No", "Yes (19)", "No", "Italy", "No", "Yes (72)", "Yes (37)", "Yes (58)", "Korea", "No", "No", "Yes (8)", "No", "Lebanon-Syria", "No", "No", "No", "No", "Liberia", "No", "No", "No", "No", "Japan", "No", "No", "No", "Yes (37)", "Nicaragua", "No", "Yes (18)", "No", "No", "Norway", "No", "No", "Yes (27)", "Yes (11)", "New-Zealand", "Yes (46)", "No", "No", "No", "Peru", "No", "No", "Yes (57)", "Yes (7)", "Souhern Rhodesia", "Yes (10)", "No", "No", "No", "South Africa", "Yes (32)", "No", "No", "No", "Sweden", "No", "Yes (51)", "Yes (15)", "Yes 18", "Turkey", "No", "No", "Yes (30)", "Yes (10)", "United Kingdom", "Yes (251)", "No", "No", "Yes (47)", "Uruguay", "No", "Yes (27)", "No", "No"), ncol = 5, byrow = TRUE)
colnames(Negotiations) <- c("Contracting party", "Geneva I (Loc)", "Annecy (Loc)", "Torquay (Loc)", "Geneva II")
Negotiations
```

