---
title: "Multilateral Commerical Diplomacy by G. Curzon"
author: "K. Buzard"
date: "Monday, August 8, 2016"
output: word_document
---

[Note this book was published in 1965]

Chapter 1: Historial Orientation
===================================================

Pg. 23: In the U.S.: 1921, Emergency Tariff Act introduced high duties on wheat, corn, meat, wool and sugar as a palliative for the agricultural unrest brought on by depression. Followed by Fordney-McUmber Act of 1922, dashed all hopes of debtor countries being able to pay off debts through exports. Marked a return to protectionism of the pre-Underwood days. Ag. products enjoyed high duties and increased rates of protected chemicals and metalurgical industries as well as others that feared foreign competition. The president used the ability to adjust rates by 50 percent up or down: 32 times up and 5 down in the following eight years.

U.S. would not negotiate its tariffs, so MFN wasn't reciprocated. Pretty much killed MFN. By 1929, clear that more protectionism was coming, along with Depression. Smoot Hawley (1930), Britain abandons gold standard in 1931, gold standard collapses, devaluation of dollar. By 1933, trade at one-third of 1929 levels.

Cordell Hull's Reciprocal Trade Agreements program (1934) led to agreements with 20 countries, maintained unconditional MFN. But wasn't able to shift the world toward liberalism, in part b/c U.S. tariff was still at such a high level. In part b/c global politics were ugly.

Keynes was not in favor of the domestic economy being subject to external (i.e. international) forces. But barriers to trade were an obstacle to the functioning of the international monetary system. Spring 1943: White and Keynes published plans for the post-war financial collaboration, including the free working of a multilateral payments mechanism, which in turn required that commerical controls should not impede international adjustments. Washington felt that U.S. should play important role in re-establishing a freer trading world.

Richard N. Gardner, 'Sterling-Dollar Diplomacy,' Oxford, 1956 pp. 12-13, describing how Hull's views determined the attitudes of the post-war planners in the U.S.: "They considered that they United States, as the world's foremost economic power, should bear the primary responsibility for reconstructing a freely flowing system of international trade. Perhaps most important, they were prepared to devote a considerable amount of American wealth, influence, and energy toward achievement of that end. Such a conjunction of power and idealism in economic affairs was entirely unprecedented in American history."


Ch. 3: The Most-Favored Nation Clause
===================================================

### The Significance of the Clause in the General Agreement

"The only way for a contracting party to avoid most-favored-nation treatment is to walk out of Gatt. But this would mean that the contracting party would also lose all the other concessions negotiated, quite apart from the one it wishes to avoid. It is hardly possible to conceive any single obligation which would make a country give up all the negotiated advantages which make up the Gatt package deal. Before Gatt it was possible to renegotiate with just the one country with whom one had difficulties without touching one's rights and obligations with any other trading partner. This is an important new development and shows that the nultilateral character of the Agreement adds up in tariff concessions to more than just a sumo fbilateral concessions."

pg. 69: US Trade Expansion Act may be of interest. It permitted the elimination of duties on those items in which the trade between the E.E.C. and the U.S. exceeded 80%.


Ch. 4: Customs Tariff
===================================================

### The Technique of Gatt Tariff Negotiations: Offers

pg. 73-74: "In the case of the United States a list of products on which concessions may be given is made public before negotiations begin. This is due to the peculiarities of American legal administrative procedure. In the first place, the RTAA fixed the maximum level of American reductions and secondly, the Tariff Commission has a right to know on which items the administration intends to reduce the tariff. Public hearings are then held and the future level of U.S. reductions is determined. The U.S. negotiators therefore arrive with all their cards on the table though in exceptional circumstances later adjustments can still be made. Their requests cannot be higher than their offers and negotiations start from this maximum position: if all requests are granted all the offers will be fulfilled. Similarly all other contracting parties are likely to make offers which match the requests they have made. As some of the requests are rejected, some of the offers are withdrawn. 

### Achievements

It must be remembered that principally only in the United States (and Canada) were tariff cuts effective during the 1950's. In other countries quotas and exchange controls interfered sufficiently with the trade flow to make any measurements meaningless.

### The New Instrument: The U.S. Trade Expansion Act

1962, President Kennedy. Replaces peril point procedure with adjustment assistance.


Ch. 5: Tariff Stabilization
===================================================

### Emergency Action

Since Gatt's inception, about 20 cases of the escape clause being invoked. Half originated in the U.S., including carpets and glass imports from the E.E.C, which were causing serious difficulty to the domestic industry.


Ch. 6: Quantitative Restrictions on Trade
===================================================

pg. 129: ``Cordell Hull's world was not Cobden's and opposition to freer trading policies was better organized in powerful pressure groups.'' This is why trade agreements had to be reciprocal. Although U.S. had high tariffs, it had very little in the way of quantitative restrictions, while many trading partners had now tariffs and significant quantitative restrictions, which could not be applied in a non-discriminatory way. So tariff bargaining had to outlaw quantitative restrictions in order to be successful.

pg. 131: Only industrial exception to ban on quantitative restrictions was instigated by U.S. to allow marketing schemes, import restrictions, or the removal of temporary surpluses for fisheries and agriculture.

pg. 131: More importantly, there were clauses that allowed exception for balance of payments, and Article XVIII B for economic development / establishment of particular industries.

pg. 139: apparently, when protectionism needed somewhere to hide in these early days, it masqueraded as balance-of-payments quantitative restrictions. In 1957 (revised Agreement), 'hard-core' waivers were introduced that made this much harder to do.

