---
title: "Data Collected from FD - 1948 - Annecy"
author: "Hoang Pham"
date: "February 13, 2017"
output: html_document
---
## peril point, Denmark, 11-06-1948
r1<-c('paragraph','article','description','date','round','investigation')
r2<-c('353','electrical element or device','parts,finished,unfinished,not specifically provided for internal combustion engines')
r3<-c('355','knives,forks steels,cleavers','household,kitchen or butchers use')
r4<-c('372','all other machines','not specifically provided for internal combustion engines')
r5<-c('397','wares','not specially provided for manufactured silver')
r6<-c('412','spring clothespins','')
r7<-c('710','cheese','characteristic of the Swiss or Emmenthaler type Blue')
r8<-c('783','grass seeds','forage crop seeds,orchard grass')
r9<-c('784','other garden and field seeds','cabbage,cauliflower')
r10<-c('802','compounds and preparations','distilled spirits are the component of chief value')
r11<-c('1405','gummed papers','')
r12<-c('1511','cork','artificial,composition or compressed cork')
r13<-c('1537 (a)','jewelry','parts,finished,unfinshied')
r14<-c('1547 (a)','works of art','statuary,sculptures or copies,replicas')
r15<-c('1558','articles','not specifically provided for brewers yeast,not containing alcohol')
r16<-c('1679','natural flint','flints,flint stones,unground')
r17<-c('1751','rennet','raw or prepared')
## Peril point, Dominican Republic, 11-06-1948
r18<-c('501','sugars,tank bottoms,sirups of cane','all mixtures containing sugar and water')
r19<-c('502','molasses,sugar sirups','')
r20<-c('502','molasses','not for commercial extraction of sugar or human consumption')
r21<-c('710','cheese','except characteristic of the Swiss or Emmenthaler type Blue')
r22<-c('1670','dyeing or tanning materials','crude or advanced,not containing alcohol')
## Peril point, Elsalvador, 11-06-1948
r23<-c('10','balsams natural and uncompouned','')
r24<-c('28 (a)','natural alizarin and natural indigo','')
r25<-c('1654','coffee','except coffee imported to Puerto Rico')
## Peril point, Finland, 11-06-1948
r26<-c('234 (a)','granite','')
r27<-r3
r28<-c('405','birch plywood','')
r29<-c('412','manufactures of wood or bark','chief value')
r30<-c('704','reindeer meat','fresh chill or frozen')
r31<-r7
r32<-c('1403','paperboard and pulpboard','')
r33<-c('1405','grease proof and parchment papers','')
r34<-c('1409','wrapping paper','')
r35<-c('1516','matches,friction or lucifer','')
r36<-c('1536','manufactures of wax','chief value')
r37<-c('1716','wood pulp','mechanically ground or chemical')
r38<-c('1772','standard newsprint paper','')
## Peril point, Greece, 11-06-1948
r39<-c('38','extracts dyeing and tanning','not alcohol')
r40<-c('53','oils vegetable','not Olive')
r41<-c('328','cylindrical and tubular tanks or vessels','for gas liquid')
r42<-c('601','filler tobacco','not specially provided for unstemmed')
r43<-c('742','currants zante or others','')
r44<-c('744','olives','kind of which Greece is a major supplier')
r45<-c('781','mixed spices, spices and spice seeds','')
r46<-c('1519 (b)','manufactures of fur','advanced')
r47<-c('1545','sponges','')
r48<-c('1545','manufactures of sponges','')
r49<-c('1686','natural gums or resins','')
r50<-c('1732','oils expressed or extracted','olive unfit for use as food')
## Peril point, Haiti, 11-06-1948
r51<-c('58','essential and distilled oils','not alcohol')
r52<-r29
r53<-c('739','orange peel crude','dried or in brine')
r54<-c('1529 (a)','articles wholly or in part of braids','')
r55<-c('1530 (e)','boot shoes or other footwear','')
r56<-c('1537 (a)','manufactures of raffla-palm leaf','chief value')
r57<-c('1670','dyeing or tanning materials','crude or advanced')
r58<-c('1684','grasses and fibers','')
r59<-c('1731','oils distilled or essential','not alcohol')
r60<-c('1783','turmeric','')
## Peril point, Italy, 11-06-1948
r61<-c('1','acids and acid anhydrides','boric and tartatic')
r62<-c('9','cream of tartar','')
r63<-c('10','balsams natural or uncompouned','not alcohol')
r64<-c('17','calomel corrosive sublimate','')
r65<-c('26','glycerophosphoric acid and salts and compounds','')
r66<-c('35','aconite aloes, asafetida cocculus indicus jalap manna','')
r67<-c('53','oils vegetable','')
r68<-c('58','oils distilled or essential','not alcohol')
r69<-c('67','barytes ore','ground or manufactured')
r70<-c('73','siennas','crude or washed or ground')
r71<-c('76','vermilion reds','')
r72<-c('80','soap','castile')
r73<-c('202 (b)','mantels friezes','chief value of earthen tiles')
r74<-c('206','pumice stone','')
r75<-c('209','talc steatite or soapstone and French chalk','')
r76<-c('211','earthenware and crockery ware','')
r77<-c('214','earthy or mineral substances','')
r78<-c('217','bottles jars','covered or uncovered')
r79<-c('231','smaltes frostings and all ceramics and glass colors','')
r80<-c('232 (a)','marble','')
r81<-c('232 (b)','slabs and paving tiles of marble breccia or onyx','')
r82<-c('232 (c)','mosaic cubes of marble breccia or onyx','')
r83<-c('233','alabaster and jet','')
r84<-c('234 (b)','tranvertine stone','')
r85<-c('234 (c)','freestone sandstone limestone','')
r86<-c('235','slate,slates chimney pieces','')
r87<-c('339','table household kitchen and hospital utensils','')
r88<-c('355','table carving,knives,forks','')
r89<-c('357','all scissors and shears','')
r90<-c('363','sword blades','not swords and side arms')
r91<-c('382','bronze or dutch metal or aluminum','(a) in leaf')
r92<-r29
r93<-c('505','adonite,arabinese duicite galactose,inosite,inulin','')
r94<-c('604','snuff and snuff flour','')
r95<-c('703','pork','prepared or preserved')
r96<-c('710','cheese','original loaves')
r97<-c('718','Fish','(a) prepared or preserved')
r98<-c('725','macaroni vermicelli,noddles','egg or not egg')
r99<-c('737','cherries','sulphured or in brine')
r100<-c('739','orange and lemon peel crude','dry or in brine')
r101<-c('739','citrons or citron peel','candied,crystallied, prepared or preserved')
r102<-c('740','figs','prepared or preserved')
r103<-c('743','lemons','')
r104<-c('761','edible nuts','')
r105<-c('764','other garden and field seeds','pepper')
r106<-c('767','lupines','')
r107<-c('770','red onions','except onion sets')
r108<-c('772','tomatoes','prepared or preserved')
r109<-c('775','vegetables','')
r110<-c('775','pastes balls puddings','all similar forms')
r111<-c('804','vermouth','')
r112<-c('908','tapestries and upholstery cloths','in chief value of cotton or vegetable fiber')
r113<-c('911','quilts or bedspreads','(a) cotton')
r114<-c('1001','hemp and hemp tow','')
r115<-c('1004','single yarns of hemp or ramie','(a)')
r116<-c('1005','cordage','(a) in chief value of hemp')
r117<-c('1009','woven fabrics','(a) in chief value of hemp or ramie')
r118<-c('1014','towels','in chief value of hemp')
r119<-c('1115','hats,bonnets caps berets','(b) bodies,hoods forms and shapes')
r120<-c('1205','woven fabrics','in chief value of silk')
r121<-c('1301','filaments of rayon or synthetic textile','')
r122<-c('1403','manufatures of papier mache','')
r123<-c('1405','Cloth-lined or reinforced paper','')
r124<-c('1406','Labels, flaps and bands','in chief value of paper')
r125<-c('1407','Drawing and similar paper','(a) eight pounds or over')
r126<-c('1410','Book covers in leather','')
r127<-c('1410','all post cards','')
r128<-c('1504','braid palits and laces','(a) in chief value of straw chip paper')
r129<-c('1518','natural grasses grains leaves plants shrubs heerbs trees','')
r130<-c('1518','boas, boutonnieres weaths','')
r131<-c('1523','human hair cleaned','commonly known as drawn')
r132<-c('1530','Boots,shoes or other footwear','(e) in chief value of leather')
r133<-c('1538','manufactures of mother of-pearl or shell','these are component material of chief value')
r134<-c('1541','musical instruments and parts','(a)')
r135<-c('1547','works of art','(a) statuary sculptures or copies replicas')
r136<-c('1552','all smoker articles','')
r137<-c('1554','umbrellas, parasols and sunshades','')
r138<-c('1554','handles and sticks for umbrelas, parasols, sunshades','')
r139<-c('1602','aconite cocculus indicus manna; marshmallow or althea root leaves and flowers','natural and uncompouned')
r140<-c('1630','Books pamphlets and music','raised print,exclusively for the blind')
r141<-c('1646','chestnuts','not further advanced than crude dried or baked')
r142<-c('1649','citrons and citron peel in brine','')
r143<-c('1670','dyeing or tanning materials: sumac','')
r144<-c('1722','vegetable substances','crude or unmanufactured')
r145<-c('1728','belladonna','')
r146<-c('1731','oils','distilled or essential not mixed or compouned')
r147<-c('1751','Rennet','raw or prepared')
r148<-c('1774','aitars, pulpits communion tables baptismal fonts shrines','')
r149<-c('1788','truffles','fresh or dried or prepared or preserved')
r150<-c('1810','works of art','pictoril paintings on glass')
r151<-c('1812','gobelin tapestries','')
## Peril point, Nicaragua, 11-06-1948
r152<-c('10','balsams','natural and uncompouned, not containing alcohol')
r153<-c('1602','ipecac','natural and uncompouned')
r154<-c('1670','dyeing or tanning metrails','crude or advanced')
r155<-c('1803','wood','(2) logs: Spanish cedar')
r156<-c('1804','railroad ties hewn','not sawd on any side')
## Peril point, Peru, 11-06-1948
r157<-c('35','pyrethrum or insect flowers and derris root tube','')
r158<-c('36','coca leaves','')
r159<-c('377','bismuth','')
r160<-c('501','sugars tank bottoms, sirups of cane juice','mixtures containing sugar and water')
r161<-c('718','fish','(a) prepared or preserved, packed in oil or other substances')
r162<-c('783','cotton','having a staple of one and one eighth inches or more')
r163<-c('1102','hair of th alpaca, ilama and vicuna','(b)')
r164<-c('1116','oriental Axminster Savonnerie, Aubusson and other carpets rugs and mats','(a)')
r165<-c('1609','cochineal and extracts','not containing alcohol')
r166<-r143
r167<-c('1685','Guano','')
r168<-c('1686','Natural gums, gum resins and resins','')
r169<-c('1719','minerals','crude, not refining or grinding')
r170<-r144
r171<-c('1765','skins of all kinds','raw and hides')
## Peril point, Sweden, 11-06-1948
r172<-c('32','compounds of cellulose','known as vulcanized or hard fiber')
r173<-c('78','potassium hydroxide or custic potash','')
r174<-c('81','sodium hydroxide or caustic soda','')
r175<-c('218','table and kitchet articles and utensils','(f)')
r176<-c('226','lighthouse lenses of glass or pebble','molded or pressed')
r177<-c('234','granite','(a)')
r178<-c('301','granular or sponge iron','')
r179<-c('302','ferrochrome or ferrochromium','(k) less 3 percent of carbon')
r180<-c('303','muck bars, pieces','')
r181<-c('304','steel ingots cogged ingots blooms and slabs','')
r182<-c('315','wire rods','')
r183<-c('315','all iron or steel wire rods','any manner')
r184<-c('315','all iron or steel bars and rods','')
r185<-c('315','all strips, plates or sheets of iron or steel','')
r186<-c('316','round iron or steel wire','(a) valued above 6 cents per pound')
r187<-c('316','all flat wires and all steel in strips','(a)')
r188<-c('316','all wire of iron steel or other metal','(a)')
r189<-c('318','fourdrinier wires and cylinder wires','')
r190<-c('319','forgings of iron or steel','(a)')
r191<-c('321','antifrition balls and rollers metal balls and rollers','')
r192<-c('325','anvils of iron or steel','')
r193<-c('328','iron or steel tubes','finished or unfinished')
r194<-c('339','table household, kitchen and hospital utensils','composed of iron or steel')
r195<-c('340','crosscut saws mill saws pit and drag saws','')
r196<-c('354','penknives and pocketknives','')
r197<-c('356','roll bars bed plates','')
r198<-c('359','surgical instruments and parts','')
r199<-c('361','slip joint pillers','value more than $2 per dozen')
r200<-c('362','files file blanks rasps and floats','')
r201<-c('372','centrifugal machines for the separation of liquids','')
r202<-c('372','all other machines','in chief value of metal or porcelain')
r203<-c('373','scythes,sickles, grass hooks and corn knives','in chief value of metal')
r204<-c('396','drills, bits, gimlets, gimlet-bits, countersinks, planes, chisels,etc','hand tools in chief value of metal')
r205<-c('397','articles or wares','')
r206<-c('405','Plywood','')
r207<-c('407','sugar-box shooks, and packing boxes','')
r208<-c('412','spring clothespins','')
r209<-c('412','manufactures of wood or bark','')
r210<-c('763','grass seeds and other forage crop seeds','')
r211<-c('1402','wallboard, insulting board and fiberboard','')
r212<-c('1405','grease-proof and imitation parchment paper','')
r213<-c('1409','sulphate and sulphite warpping paper','')
r214<-c('1516','matches, friction or lucifer','')
r215<-c('1604','agricultural implements','')
r216<-c('1623','hard crisp bread','made from rye flour')
r217<-c('1700','Iron ore','')
r218<-c('1716','chemical wood pulp','unbleached')
## Peril point, Uruguay, 11-06-1948
r219<-c('705','extract of meat','including fluid')
r220<-c('706','meats','prepared or preserved')
r221<-c('1530','hides and skins of cattle of the bovine species','(a)')
r222<-c('1603','agates','unmanufactured')
r223<-c('1625','blood','dried')
r224<-c('1627','bones','crude or steamed or ground')
r225<-c('1780','tankage','not for human consumption')


data1948<-rbind(r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20,r21,r22,r23,r24,r25,r26,r27,r28,r29,r30,r31,r32,r33,r34,r35,r36,r37,r38,r39,r40,r41,r42,r43,r44,r45,r46,r47,r48,r49,r50,r51,r52,r53,r54,r55,r56,r57,r58,r59,r60,r61,r62,r63,r64,r65,r66,r67,r68,r69,r70,r71,r72,r73,r74,r75,r76,r77,r78,r79,r80,r81,r82,r83,r84,r85,r86,r87,r88,r89,r90,r91,r92,r93,r94,r95,r96,r97,r98,r99,r100,r101,r102,r103,r104,r105,r106,r107,r108,r109,r110,r111,r112,r113,r114,r115,r116,r117,r118,r119,r120,r121,r122,r123,r124,r125,r126,r127,r128,r129,r130,r131,r132,r133,r134,r135,r136,r137,r138,r139,r140,r141,r142,r143,r144,r145,r146,r147,r148,r149,r150,r151,r152,r153,r154,r155,r156,r157,r158,r159,r160,r161,r162,r163,r164,r165,r166,r167,r168,r169,r170,r171,r172,r173,r174,r175,r176,r177,r178,r179,r180,r181,r182,r183,r184,r185,r186,r187,r188,r189,r190,r191,r192,r193,r194,r195,r196,r197,r198,r199,r200,r201,r202,r203,r204,r205,r206,r207,r208,r209,r210,r211,r212,r213,r214,r215,r216,r217,r218,r219,r220,r221,r222,r223,r224,r225)
data1948a<-data.frame(r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20,r21,r22,r23,r24,r25,r26,r27,r28,r29,r30,r31,r32,r33,r34,r35,r36,r37,r38,r39,r40,r41,r42,r43,r44,r45,r46,r47,r48,r49,r50,r51,r52,r53,r54,r55,r56,r57,r58,r59,r60,r61,r62,r63,r64,r65,r66,r67,r68,r69,r70,r71,r72,r73,r74,r75,r76,r77,r78,r79,r80,r81,r82,r83,r84,r85,r86,r87,r88,r89,r90,r91,r92,r93,r94,r95,r96,r97,r98,r99,r100,r101,r102,r103,r104,r105,r106,r107,r108,r109,r110,r111,r112,r113,r114,r115,r116,r117,r118,r119,r120,r121,r122,r123,r124,r125,r126,r127,r128,r129,r130,r131,r132,r133,r134,r135,r136,r137,r138,r139,r140,r141,r142,r143,r144,r145,r146,r147,r148,r149,r150,r151,r152,r153,r154,r155,r156,r157,r158,r159,r160,r161,r162,r163,r164,r165,r166,r167,r168,r169,r170,r171,r172,r173,r174,r175,r176,r177,r178,r179,r180,r181,r182,r183,r184,r185,r186,r187,r188,r189,r190,r191,r192,r193,r194,r195,r196,r197,r198,r199,r200,r201,r202,r203,r204,r205,r206,r207,r208,r209,r210,r211,r212,r213,r214,r215,r216,r217,r218,r219,r220,r221,r222,r223,r224,r225)

date<-c(rep(c('11-06-1948'),each=224))
round<-c(rep(c('Annecy'),each=224))
investigation<-c(rep(c('peril point'),each=224))
data1948full<-data.frame(data1948,date,round,investigation)
colnames(data1948full)<-r1

      