---
title: "Industry list"
author: "Benjamin Heyries"
date: "Wednesday, February 04, 2015"
output: word_document
---

The following document indicates the industries that have benefited of political support. They are classified alphabetically. The information related to these industries are:

* the time of the political action
* the actors who supported the action
* the description of the suggested protection 
* the implementation of the measure

The sub-section indicates an action where only a fraction of the industry is particularly targeted by a protection measure.

Agriculture
============
  * 1934, when voting the TAA for the first time;at the initiative of the Republicans, in House and by Senator Overton, supported by a minority of Democrats. Concern the production stipulated in the AAA: __sugar__, __coconut oil__, __sesame__ __oil__, __laces__, __braids__, __wool__ and __wheat__. The goal of the amendments is to require the cost-production calculus for these particular products and to spare them from tariff cuts. The amendment is defeated even though it was supported by some Democrats. 
  * 1937, when voting the first extension of the TAA, introduced in the Senate by the Republicans and followed by a lot of Democrats (20 in Senate). The amendments aim applying the cost-production calculus for agricultural products and spare them from tariff cuts.The amendment is first adopted then rejected in the final vote.
  * 1952, Greece and Turkey sued the United States at the GATT on dried figs. To be precised with the working party document.
  * 1953, when voting an extension of the TAA, brought by Senator Magnuson (D), Cordon (R) and Representative Simpson modified for the House Ways and Means Committee under the presidency of Chairman Reed. The amendments forbid new tariff cuts on agricultural product (especially __wool__), enable rising tariffs by use of Section 22 of the AAA on the TAA. Adopted.
  * 1955, when voting an extension of the TAA, brought in the Cooper (Representative R) bill amended by the House Ways and means committee. It sets the preeminence of Section 22 of the AAA on the TAA. Adopted.
  * 1962, the United States filed a complaint at the GATT against Canada on potatoes. Canada imposed a duty on fresh potatoes that affect the United States (the form of levy duty is problematic as there is not a fixed amount). The working party required Canada to withdraw the levy duty that appeared to be a straight custom applied to the whole country without trade justifications. The United States were not by default allowed to suspend concessions or retaliate. 
  * 1963, the United States filed a complaint at the GATT against the EEC on poultry. The Working party decided what share of trade were affected by the variable levy affecting the German market. They found a figure between the two contracting parties that satisfied both. The conclusion of the dispute is not clear and it is not stated in the GATT document.  XXXXXX
  * 1967, Malawi sued the United States at the GATT on non-manufactured tobacco subsidy. To be precised with the working party document.
  * 1975, the United States filed a complaint at the GATT against Canada on quotas eggs. The restriction on trade by Canada is not prohibited by the article XI (temporary quantitative restrictions). The duration of the measure is to be settled in bilateral discussion. until this topic is settled, it is not possible to define if the measure is a cause of nullification or impairment.
  * 1977, the United States filed a complaint at the GATT against the EEC on Animal Feed Proteins. It is a very technical and complex issue. The EEC, according to United States, implemented a obligation of buying of skimmed milk for adding protein in animal feeding that actually protected the domestic producers of dairy product. It threatens the interest of producer of directly substitutable products, like vegetable protein, that are produced in majority by the United States. As a consequence, the panel decided that the EEC missed its obligation to the United States as mentioned in the first article if the GATT.
  * 1981, the United States filed a complaint at the GATT against Japan on tobacco. The United States indicated that some measure implemented by Japan on manufactured Tobacco discriminated American products. The US filed a complaint under the article 23, 2 (nullification and impairment) and bilateral negotiations were helped by a panel. Both sides reached an agreement on the conditions of importations of manufactured tobacco, which solved the issue.
  * 1981, the United States filed a complaint at the GATT against the EEC on poultry. The United States deemed that the UK implemented measures that discriminate American products. The contracting parties, as they fail to reach an agreement, asked for the constitution of a panel. In May 1981 (the dispute started in July), the American delegation withdrew the complaints. No further pursuits were undertaken.
  * 1981, the United States filed a complaint at the GATT against Spain on soybean oil. They think that Spain restriction discriminated American products.Spain argued that the protection of the industry was critical: they were a necessary protection of the consumer as well as the olive sector. A panel was constituted. Like the issue on animal feeds, it was fierce controversy with several griefs from the American delegation. The panel decided that there no nullification or impairment of the American interest. The issue can be with the interaction with third markets. As a consequence, the panel suggested the contracting parties to work out an agreement in order to minor these effects.
  * 1983, the United States filed a complaint at the GATT against the EEC on Wheat flour export subsidies. The subsidies would have impaired or nullified the interest of American exports. As a consequence, a panel was created. If the EEC practices could be directly linked to an infringement of any GATT article, the panel however found that it may have disturbed the market. As a consequence, they suggest the contracting parties to observe greater transparency and cooperation in order to avoid any further conflict. They reported to the GATT to add some clarifications to the concept of "more than equitable share" in the article 10.1 of the Code (the agreement on interpretation of articles 6, 16 and 23 of the GATT).
  * 1983, the United States filed a complaint at the GATT against the EEC on export subsidies for pasta. The issue is similar to the dispute on wheat flour export subsidies (the article invoked from the Code is the 9th instead of the 10.1 but he argument are similar). However, as pastas are not a primary product but a processed agricultural product, the interpretation of the Code by the EEC is faulty. It would be even dangerous to grant this interpretation as, according this reading of the 9th article of the "Code",it would be possible to subsidize any processed product. as a consequence the export subsidy on pasta is not consistent with the GATT rules. It is noteworthy that the panel was not united in his final decision. One member argued that the difference between primary product and agricultural product is a terminological one. As a consequence, the practices of the EEC are not inconsistent with the code. It may be a clear gain of GATT in his quest for authority: the GATT is the only one that can interpret his text. Moreover, the GATT strengthened the application of exceptional trade measures. 
  * 1984, Nicaragua sued the United States at the GATT on sugar quota. To be precised with the working party document
  * 1985, the United States filed a complaint at the GATT against the EEC on citrus. The EEC has special agreements with European countries and former colonies (like Algeria and Morocco). The EEC argued that the difference in the level of tariffs has been notified to the GATT in previous session and were accepted. Moreover, they affirmed that there were no proof that the American exports actually suffered from the difference in tariff level.The panel deemed that the American interest were impaired. As a consequence, it recommends to the EEC to apply an equal MFN tariff to both American export and Mediterranean countries.
  * 1985, the United States filed a complaint at the GATT against the EEC on canned fruits. The EEC introduced a minimum price for some processed agricultural products. A panel was formed in order to determine if American trade interests were impaired. It suggests to the EEC to get back to the previous regime where no consumption subsidy was enforced. 
  * 1986, the EEC sued the United States at the GATT on sugar. To be precised with the working party document
  * 1987, the United States filed a complaint at the GATT against Japan on agricultural products. It concerned a wide range of agricultural products: from dairy products and fruits to bovine meat and sugar. It even concerns some processed products like Tomato Ketchup. The American delegation complained against quantitative restrictions from Japan, which are formally forbidden by the article 11 of the GATT. The panel advice Japan to released those constraints. 
  * 1989, the United States filed a complaint at the GATT against Norway on apples and pears. Norway implemented restrictions on the import of apples and pears. They consisted in licenses that were given only if domestic production was sold. This is a clear infringement of the GATT. The panel then recommended the contracting parties to bring Norway to renounce to this practice.
  * 1989, the United States filed a complaint at the GATT against Korea on beef. The Republic of Korea was under the procedure of Balance of payment exemptions. As a consequence, it could make some use of quantitative restrictions. A year before the complaints, it partially reduced those constraints and implemented a new quota without the approval of the Balance of payment committee. The balance of payment justification ended in 1967 and was not renewed. As a consequence, the panel assess that the import restrictions are not in conformity with the GATT. It invites the contracting parties to work out with Korea in order to remove them.
  * 1989, the United States filed a complaint at the GATT against Canada on Ice cream and yogurt. Canada implemented license and quotas for yogurt and ice  cream.It aims at protecting raw milk producers, as yogurt and ice cream are considered as "like-product". The panel concluded that the quotas were not in direct relation with raw milk. Therefore they are incompatible with the GATT, and particularly with the article 11.
  * 1989, Australia sued the United States at the GATT on non-manufactured tobacco subsidy. To be precised with the working party document
  * 1989, the United States filed a complaint at the GATT against the EEC on oil-seeds and animal-feed proteins. This is related to the dispute of 1977 which opposed the same parties about the same products. The EEC subsidized producers to buy animal-feed proteins issued from the EEC. The panel formed to solve the dispute settled that the EEC should not pursue their practices. The dispute continued in 1992, where the EEC did not change quickly and totally enough to satisfy the American delegation. As a consequence, the panel remind the European Community that it has to respect its engagement. 
  * 1989, the United States filed a complaint at the GATT against the EEC on apples. To be precised with the working party document.
  * 1990, the EEC sued the United States at the GATT on the sugar waiver. To be precised with the working party document.
  * 1990, Canada sued the United States at the GATT on pork. To be precised with the working party document.
  * 1992, the United States filed a complaint at the GATT against Thailand on Tobacco. Thailand cigarette import system is restricted by licensing, which where only granted to the Thailand Tobacco monopoly who barely used it 3 times on a period of 20 years, and internal taxes that made discrimination between domestic products and foreign ones. The panel found that, if licensing was in contradiction with the GATT, the internal tax regime was not actually inconsistent with the article 3 of the GATT. As a consequence, only the licensing practice should be targeted by an action of the contracting parties.
  * 1992, the United States filed a complaint at the GATT against Canada on grain corn. It may be a retaliation from the issue in 1990 about pork. Canada applied indeed its right to fight against unfairly subsidized product (as stated in article 6 of the Subsidies agreement) and levy a tariff on subsidized American product. The American delegation complained about the Canadian reaction. The panel formed listened to both and assessed that American grain corn could not be considered as subsidized products contained in article 6. Therefore, the Canadian countervailing duty has to be changed for a one in conformity  with the code: a determination of the harm done is needed.
  * 1993, the United States filed a complaint at the GATT against Korea on polyacetal resin. It is a complaint about an anti-dumping duty applied by the Korean government. The panel concluded that the Korean government did not do enough research and their conclusion were too shallow to apply an anti-dumping duty. As a consequence, it recommends the Committee on anti-dumping duty to request Korea to change its measure as it has to be consistent with the Agreement on application of the article 6 of the GATT.
  * 1994, a group of 9 countries including Argentina, Brazil, Canada, Chile, Columbia, El Salvador, Guatemala, Thailand and Zimbabwe sued the United States at the GATT on Tobacco. To be precised with the working party document.

Defense
============
  * 1954, when voting an extension of the TAA. Brought by Senator Symington (Democrat). It stipulates that no action should be taken to decrease a tariff if it appears to threaten meeting Defense requirements. 

Fishing
============
  * 1949 when voting an extension of the TAA ; Senator Milliken, senior Republican in charge of foreign policy in the opposition;raising tariffs in order to protect from new imports. The amendment failed in the Senate by a partisan vote.
  * 1981, Canada sued the United States at the GATT on tuna. To be precised with the working party document
  * 1987, the United States filed a complaint at the GATT against Canada on herring and salmon. The target is the regulation of export and sales for export of unmanufactured herring and salmon. A panel is formed in order to solve this issue. Canada argued that the measure was to protect the resource of salmon and herring. However, the panel found that export restriction were incompatible with the article 11. As a consequence, it enticed Canada to remove these barriers, the American delegation suggesting that they would be replaced by other expedients of same effect.
  * 1991, Mexico sued the United States at the GATT on tuna. To be precised with the working party document
  * 1992, Norway sued the United States at the GATT on salmon. To be precised with the working party document
  * 1994, the EEC sued the United States at the GATT on tuna. To be precised with the working party document.

Fur
============
  * 1949 when voting an extension of the TAA ; Senator Milliken, senior Republican in charge of the foreign policy in the opposition;raising tariffs in order to protect the new imports. The amendment failed in the Senate by a partisan vote.
  * 1951, Czechoslovakia sued the United States at the GATT on fur felt hats. To be precised with the working party document.

Mining and steel work
============
  * 1949 when voting an extension of the TAA ; Senator Milliken, senior Republican in charge of the foreign policy in the opposition;raising tariffs in order to protect the new imports. The amendment failed in the Senate by a partisan vote.
  * 1953, when voting an extension of the TAA, brought by Representative Simpson modified for the House Ways and Means Committee under the presidency of Chairman Reed.Implement higher duties on lead and zinc. Adopted.
  * 1990, the United States filed a complaint at the GATT against the EEC on copper scrap. The two parties reached an agreement which ended the complaint procedure.
  * 1990, Sweden sued the United States at the GATT on steel. To be precised with the working party document.
  * 1994, the EEC sued the United States at the GATT on lead and Bismuth. To be precised with the working party document.

Oil industry
============
  * 1949 when voting an extension of the TAA ; Senator Milliken, senior Republican in charge of the foreign policy in the opposition;raising tariffs in order to protect the new imports. The amendment failed in the Senate by a partisan vote.
  * 1953, when voting an extension of the TAA, brought by Representative Simpson modified for the House Ways and Means Committee under the presidency of Chairman Reed. implementation of quotas on crude oil and residual fuel oil. 
  * 1955, when voting an extension of the TAA, brought by Senator Neely. It implements a 10% quota on oil and residual fuel. It is not accepted but converted into a amendment regarding national security industry that enables the President to raise the level of tariff. This one is adopted. 
  
Textile
============
  * 1948, the United States filed a complaint at the GATT against Cuba on textile. The United States complained about tariff implementation on the colored woven items. Cuba replied that there were open to renegotiation. The dispute was not settled in 1948.
  * 1949, the United States filed a second complaint at the GATT against Cuba on textile. The two parts disagreed on the level of tariffs implemented on woven textiles.Cuba required a waiver on textile items to raise tariffs. The US refused arguing that the waiver would affect products not produced in Cuba. The two parts failed to reach an agreement.
  * 1955, when voting an extension of the TAA, brought by Senator George (D) and supported by Senator Johnson. Limit the tariff cut on 300 Japanese products including textile. Adopted
  * 1978, the United States filed a complaint at the GATT against Japan on Silk Yarn. Japan implemented severe restriction at the import of silk yarns. The US filed a complaint and bilateral negotiations were helped by a panel. Both sides reached an agreement on the conditions of importations of silk yarns, which solved the issue.
  * 1979, the United States filed a complaint at the GATT against Japan on leather. Japan implemented severe restriction at the import of leather. It was justified until 1962  because of balance of payment purposes. However, it was not withdrawn with the end of the motive. Therefore, the US filed a complaint and bilateral negotiations were helped by a panel. Both sides reached an agreement on the conditions of importations of leather, which solved the issue.
  * 1984, the United States filed a complaint at the GATT against Japan on leather. This is the next chapter of the battle on leather between the American delegation and the Japanese delegation. The agreement reached in 1979 expired in 1982 and no new agreement was reached. As a consequence, a panel was formed in order to determine of there were any impairment or nullification of American interest under the provision of article 23.2. The absence of legal support of the Japanese defense as well as the direct infringement of the GATT (quantitative restrictions) forced the panel to advice Japan to withdraw its quotas (the case of the Dowa people was appealing but could not be followed as no legal argument was given).

Watches
============
  * 1949 when voting an extension of the TAA ; Senator Milliken, senior Republican in charge of the foreign policy in the opposition;raising tariffs in order to protect the new imports. The amendment failed in the Senate by a partisan vote.
  * 1953, when voting an extension of the TAA, brought by Representative Simpson modified for the House Ways and Means Committee under the presidency of Chairman Reed. Implement higher tariffs on Swiss watches. Adopted.
  

Remarks
============

  * From the 1980s, there is a clear change in the way the American delegation handle GATT complaints. The number and the complexity of the arguments presented is greater by far than in the previous periods. Moreover, the form of the text becomes more and more like legal decisions, with a well defined structure.
  * Besides the length of the resolutions, the decision of the panel are usually more in favor of the complainant after 1980. In previous periods, the end of the dispute signified that an agreement had been reached or that the complaint was withdrawn by the complainant (the most likely being that the complaint was not solid enough anymore).