---
title: "Lit Review"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lit Review

## First 29

1.  Cheng, Hang Sheng. "Statistical Estimates of Elasticities and Propensities in International Trade: A Survey of Published Studies." Staff Papers (International Monetary Fund), vol. 7, no. 1, 1959, pp. 107--158. JSTOR, www.jstor.org/stable/3866125.

-   intro: "The present paper is intended as a contribution toward meeting this need. Part I is an index, according to country or area, of estimates of elasticities iand propensities taken from 42 books and articles pub- lished in the period 1937 to 1957. These sources are described in Part II. The numbers in parentheses-e.g., exports of food (30), (31), under United Kingdom-in Part I, are references to the sources given in Part II for the estimated elasticities or propensities related to the topic.' Each description in Part II sets forth the purpose and scope of the study, the variables and the methods used in the statistical tion, the tests of significance used (if any), and the conclusions drawn by the author. A quick look at these notes may help the reader to decide whether a study is likely to give him the information that will be usefulto him." (pg 1-2)
-   <https://doi.org/10.2307/3866125>

2.  Stephen A. Resnick, Edwin M. Truman,"An empirical examination of bilateral trade in Western Europe" Journal of International Economics, Volume 3, Issue 4, 1973, Pages 305-335, ISSN 0022-1996,

-   intro: This paper presents an econometric model of bilateral trade flows for ten !Vest European countries from 1953 to 1968. Our aim is to develop and estimate a trade model which yields a reasonable set of direct and indirect price effects while endeavoring to avoid the problem of multicollinearity of price. The structure and estimates of such a model allow us to explore the implications of differential price changes or discriminatory tariff changes for the trade of the countries included in the model. A second paper by the authors (Resnick and Truman, 1973) presents these policy results. If the model were :xpanded to include at least the United States, Canada and Japan as separate importers and sources of supply, it might be useful in analy; ing the effects of exchange rate changes.
-   [https://doi.org/10.1016/0022-1996(73)90025-1](https://doi.org/10.1016/0022-1996(73)90025-1){.uri}.

3.  Balassa, Bela. "Tariff Reductions and Trade in Manufacturers among the Industrial Countries." The American Economic Review, vol. 56, no. 3, 1966, pp. 466--473. JSTOR, www.jstor.org/stable/1823779.

-   "This paper uses empirical evidence to examine the proposition advanced by Lawrence B. Krause that the establishment of the Common Market will seriously harm U.S. exports because "dominant suppliers"1 in EEC countriesreceive increased protection from the averaging of national tariffs [1] r6]. Subsequently, the results are used to reinterpret the traditional conclusions regarding the effects of tariff reductions on the domestic economy, and additional tests are offered to indicate the predominance of intraindustry-as against interindustry-specialization in trade in manufactures among the industrial countries."
-   <https://www.jstor.org/stable/1823779>

4.  Chenery, Hollis B. "Patterns of Industrial Growth." The American Economic Review, vol. 50, no. 4, 1960, pp. 624--654. JSTOR, www.jstor.org/stable/1812463.

-   "An increase in per capita income in a country is normally accompanied by a rise in the share of industrial output. The accepted explanation for this relationship is the change in the composition of demand,of which the decline in the share of food (Engel's Law) is the most not-able feature. However, this over-all relationship does not necessarilyapply to every individual country. XVithin limits, the changing composition of domestic demand can be offset through foreign trade. A coun-try having a continuing comparative advantage in primary productionmay therefore reach a high level of income without an increase in theshare of industry in total output. Because of the diversity of naturalresources, we should not expect to find uniform patterns of growth inall countries.'Evidence from several sources suggests a closer and more pronouncedrelationship between levels of income and industrial output than wouldbe predicted from the change in demand alone. Kuznets' comparisonof some 50 countries [13] shows a marked increase of manufacturingwith rising per capita income, as did the earlier analyses of Bean[1] and Clark [2]. The fact that patterns of trade change systematically with rising income levels is equally well established [9]. Historical studies also show considerable uniformity in the rise of industry as growth proceeds [7] [10] [15]. Finally, modern growth theory contains arguments against continued specialization in primary production, stemming from the uncertainty of export demand and the interdependence among sectors of production [14] [16]."
-   <https://www.jstor.org/stable/1812463>

5.  Finger, J. M. "Gatt Tariff Concessions and the Exports of Developing Countries--United States Concessions at the Dillon Round." The Economic Journal, vol. 84, no. 335, 1974, pp. 566--575. JSTOR, www.jstor.org/stable/2231040.

-   "AT the 1960-61 GATT tariff conference (The Dillon Round) the United States negotiated with the European Economic Community and 11 otherdeveloped countries (DC) as well as with six less developed countries (LDC)(Cambodia, Haiti, India, Israel, Pakistan and Peru) and agreed to reduce its duties on products covering some \$2 billion of imports in 1960. While this 20 % reduction of tariffs on some 20 % of dutiable imports was small compared with the 35 % cut on almost 55 % of dutiable imports achieved in the more recent Kennedy Round, they were more extensive, both in terms of the magnitude of the reductions and extent of import coverage, than the reductions achieved in any of the previous five GATT rounds except the first,in Geneva in 1947.
-   <https://www.jstor.org/stable/2231040>

6.  Kreinin, Mordechai E. "Effect of Tariff Changes on the Prices and Volume of Imports." The American Economic Review, vol. 51, no. 3, 1961, pp. 310--324. JSTOR, www.jstor.org/stable/1814161.

-   intro: For the past 25 years the United States has been granting tariff concessions to foreign nations under authority provided by the Reciprocal Trade Agreements Act of 1934. Negotiations leading to these concessions were conducted on a bilateral basis during the prewar years, and shifted to the multilateral framework of the General Agreement on Tariffs and Trade (GATT) in 1947. But throughout the entire period they were subject to the unconditional most favored nation principle under which a concession granted to any one country is immediately applicable to all other sources of supply. In total, these concessions had a sizeable effect on the United States tariff level, reducing the ratio1 of duties collected to the value of dutiable imports by 50 percent between 1933 and 1953:Concessions made in all trade agreements apply to articles which accounted for 93.4 per cent of the total dutiable imports in 1952.... Theaverage ad valorem equivalent of the duties on total dutiable imports (weighted by 1952 data) before any trade agreements were in effect was 24.4 per cent. The average at January 1, 1945, rates was 17.9 per cent; and as of January 1, 1953, it was 12.2 per cent [17, p. 3]. Although overshadowed by the substantial rise in income during the past generation, such a large decline in the level of protection could not fail to have some effect on the volume of U.S. imports. This article utilizes data from the two most recent GATT negotiations, conducted in 1955 and 1956, to examine the effect of the United States tariff-reduction program on the prices and volume of imports subject to tariff concessions. After comparing the results to those obtained by other students of the subject, the data are used to draw policy conclusions and to measure roughly the gain in welfare and the loss of employment resulting from the tariff cuts."
-   <https://www.jstor.org/stable/1814161>

7.  Leamer, Edward E. "Nominal Tariff Averages with Estimated Weights." Southern Economic Journal, vol. 41, no. 1, 1974, pp. 34--46. JSTOR, www.jstor.org/stable/1056094.

-   main point of intro "The intent of this paper is to estimate a model of international trade and to use that model to construct tariff averages. In section 1 we shall describe a fairly complete trade dependence model that includes tariffs and that allows tariff elasticities to vary from commodity to commodity. The model is estimated using cross-section 1958 data and the results are reported in section 2. These estimates are used in section 3 to compute ahandful of different tariff averages and corresponding elasticity averages. Section 4 contains brief concluding remarks."

-   <https://www.jstor.org/stable/1056094>

8.  Officer, Lawrence H., and Jules R. Hurtubise. "Price Effects on the Kennedy Round on Canadian Trade." The Review of Economics and Statistics, vol. 51, no. 3, 1969, pp. 320--333. JSTOR, www.jstor.org/stable/1926566.

-   "CANADA was one of 52 countries participating in the "Kennedy Round" negotiations of 1964-1967. Because of the openness of the Canadian economy, the potential results of these trade liberalizations on its imports and exports are of special interest.' In this study we forecast the price effects of the Kennedy Round on Canada's trade as of 1973, when all the negotiated tariff reductions are scheduled to have occurred. We consider the impacts on total Canadian imports and exports to the United States, and analyze them disaggrega- tively by commodity groups. This is done by means of a four-stage procedure: 1) Develop time series of trade, price, and activity that are useful, indeed essential, for any systematic examination of Canadian trade.2 2) Estimate demand functions for Canadian imports and exports, using as data the series obtained in (1). 3) Construct tariff rates for the commodity groups in (2) on pre-Kennedy (pre-1968) and post-Kennedy (post-1972) bases. 4) Deduce the price effects of the Kennedy Round by the application of the tariff rates in (3) to the demand functions in (2). In section II we discuss the specification and estimation of the demand functions. We present estimated equations for Canadian imports in section III and for exports to the United States in section IV. These equations and some especially constructed data are applied to calculate the effects of the Kennedy Round in section V."
-   <https://www.jstor.org/stable/1926566>

9.  Pöyhönen, Pentti. "A Tentative Model for the Volume of Trade between Countries." Weltwirtschaftliches Archiv, vol. 90, 1963, pp. 93--100. JSTOR, www.jstor.org/stable/40436776.

-   " Contents: I. A General Model for the Structure of the International Exchange of Goods. - II. Finding the Form of the Explanatory Model. - III. The Data Used. - IV. Estimation of the Parameters of the Model. - V. On the Values of the Parameters. - VI. Discussion of the Results. paper aims to bring some structural features of international trade into relief. The analysis is based on the simultaneous appli- cation of a structural and explanatory model resembling an input- output model to the exchange of goods between ten European countries in 1958. The nature of the experiment made it necessary to confine the analysis at this stage to a relatively limited set of data, but there is nothing, in principle, to prevent the extension of the analysis to the world trade as a whole. Changes over time were also left outside the scope of this paper, so that the model employed is static. In spite of these restrictions the results are of interest and, as I believe, novel; they serve to indicate that the bilateral approach can be abandoned in investigating international trade, which can be treated as an integral whole within the framework of a single model or model system
-   <https://www.jstor.org/stable/40436776>

10. Savage, I. Richard, and Karl W. Deutsch. "A Statistical Model of the Gross Analysis of Transaction Flows." Econometrica, vol. 28, no. 3, 1960, pp. 551--572. JSTOR, www.jstor.org/stable/1910131.

-   "This model is applicable to the flow of any kind of quantifiable trans- actions, and to matrices from three to more than one hundred actors, utilizing a 650 IBM electronic computer or similar equipment. The method develops a matrix of expected or baseline data from assumptions of complete indifference among the actors, and measures the plus or minus differences between this baseline value and the actual amount of transactions in each direction for every pair of actors. It thus removes gross size effects and permits tentative inferences about the distribution of preferences among pairs of larger groups of actors; about degrees of clustering or integration among actors; and about changes over time, if several matrices are used. It thus locates interesting pairs or groups for further study. Import-export data are used as an example to show the detailed application of the method. For a given year and a group of countries, the import- export data can be arranged like a contingency table, except the diagonal cells are zero and the other entries are quantities of money, a continuous variable instead of a discrete variable. A model describing the data and techniques for the statistical analysis are presented. This is a "null model" in the sense that the departures from it are of primary interest. The North Atlantic Area (1928) is used as an illustration."
-   Comment: it is 1928 but can be used to apply to later models.
-   <https://www.jstor.org/stable/1910131>

11. Helleiner, G.K. "The Political Economy of Canada's Tariff Structure: An Alternative Model." The Canadian Journal of Economics / Revue Canadienne D'Economique, vol. 10, no. 2, 1977, pp. 318--326. JSTOR, www.jstor.org/stable/134449.

-   "Caves's recent imaginative attempt to test models of the process of Canadian tariff policy formation (Caves, 1976) concluded that an interest group approach had greater explanatory power than the alternatives he tested. His particular specification of such a model, however, is by no means the only plausible one. Indeed, Caves himself notes the many qualifications to which his results are subject. This paper tests an alternative interest group explana- tion of the Canadian tariff structure. The model differs from that of Caves in two major respects. In the first place it attempts to take certain international political influences into account as well as the purely Canadian ones. Secondly, it focuses upon a different set of explanatory variables from Caves's model even as far as domestic influences are concerned. Caves's analysis attempted to explain no more than the pattern of Canadian tariffs in a single year, 1963, since which there have been significant tariff changes. New data now available make it possible not only to update such studies of the Canadian tariff but also to analyse recent changes therein (Wil- kinson and Norrie, 1975)."
-   <https://doi.org/10.2307/134449>

12. Conybeare, J. (1983). Tariff protection in developed and developing countries: A cross-sectional and longitudinal analysis. International Organization, 37(3), 441-467. <doi:10.1017/S0020818300032744>

-   Abstract: "Four political models (the international system, rational domestic economic policy, intragovemmental politics, and interest group influence) may explain the cross-national structure of average nominal levels of tariffs on manufactures. Using available data measuring or approximating the explanatory variables for the time periods 1902 and 1971, selected hypotheses were tested in regression equations. The 1971 tariff levels are best predicted by rational economic policy variables while for 1902, international power variables provide the best predictions of the tariff. In general, the causal forces influencing the cross-national pattern of tariff levels appear to have shifted in the 20th century from those indicating international power to those measuring domestic politico-economic development. These results provide evidence relevant to some of the general propositions about size and development suggested by the contemporary political economy literature. They also lend support to those who argue that a rising level of international interdependence has resulted in long-term changes in the pattern of influences on national public policies."
-   <https://doi.org/10.1017/S0020818300032744>

13. Finger, J. M. "Effects of the Kennedy Round Tariff Concessions on the Exports of Developing Countries." The Economic Journal, vol. 86, no. 341, 1976, pp. 87--95. JSTOR, www.jstor.org/stable/2230953.

-   "intro: At the Kennedy Round the major industrial countries agreed to tariff reductions of about one-third of the initial level on about one-third of their total or two-thirds of their dutiable imports - the largest set of concessions negotiated at any of the six completed GATT rounds. This paper summarises the results of a study of the effects on manufactured imports (SITC 5-8 less 67, 68) of the Kennedy Round tariff concessions implemented by the United States, the EEC and Japan. In particular it is concerned with the supply-lag hypothesis that developing-country exports will not respond as strongly as developed-country exports to the marginal profit incentive of the tariff cuts. The methodology of the study was to compare the change of industrial- country imports of a random sample of products on which large tariff reductions were made with the record of another sample of similar imports on which tariffs were changed by smaller amounts. The extension of the familiar "reduced group, non-reduced group" method ology2 to allow for tariff changes in the " ccontrol group" was made necessary by the inclusiveness of the Kennedy Round cuts.

-   

        https://www.jstor.org/stable/2230953

14. Kowalczyk, Carsten and Davis, Donald. "8. Tariff Phase-Outs: Theory and Evidence from GATT and NAFTA". The Regionalization of the World Economy, edited by Jeffrey A. Frankel, Chicago: University of Chicago Press, 2007, pp. 227-258

-   Intro: "Regionalization is now so widespread that the World Trade Organization, in one of its first studies since its creation, can claim that "when the WTO was established on 1 January 1995, nearly all its members were parties to at least one agreement notified to GATT."' According to the same study this process has picked up speed in recent years with almost a third of the 109 agreements brought to the General Agreement on Tariffs and Trade (GATT) between 1948 and 1994 having been notified since 1990. Clearly nations perceive the process of regionalization to be one from which they cannot afford to be left out.2 The question of whether the process of "regionalization" is desirable or not is an important one. A related question is whether the form in which the world trading system permits preferential arrangements is beneficial, and if not, which types of arrangements would be. It is particularly interesting, and this is the topic of the present paper, that results from economic theory offer only mixed support for article XXIV, the condition under which about 90 percent of all notifications of preferential agreements have been presented to GATT."
-   <https://doi.org/10.7208/9780226260228-012> or <http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.477.1901&rep=rep1&type=pdf>

15. Hartigan, James C. "The U.S. Tariff and Comparative Advantage: A Survey of Method." Weltwirtschaftliches Archiv, vol. 117, no. 1, 1981, pp. 65--109. JSTOR, www.jstor.org/stable/40438552. A

-   Intro: "Tpursuit of the sources of comparative advantage for a country is closely related to the analysis of the welfare and income distri- bution effects of trade policy. In other words, as trade barriers are reduced, an economy approaches its free trade production pattern, and comparative advantage is disclosed. Thus, studies of comparative advantage and analyses of trade policy are identical, although this is frequently misconstrued. Accordingly, this paper surveys both the studies that focus on U.S. comparative advantage, and those concerned with trade policy. A major tenet of this paper is that a general equilibrium approach to all these issues is mandated, in view of the potentially pervasive impact of trade on an economy. This can be performed through the explicit simulation of a general equilibrium model, or through a regression analysis that incorporates simultaneity. When there is mutual determinacy of trade barriers and comparative advantage, it is permissible to regress each as a function of their determinants in a two-stage procedure. Thus, regression is a substitute for a general equilibrium analysis when it is completely specified. Implicit in the selection of material for this paper is the assumption of the validity of the factor proportions theory of trade. To this end, applications of the classical, or differential productivity, theory of trade are not considered1."
-   <https://www.jstor.org/stable/40438552>

16. Golub, Stephen S., and J. M. Finger. "The Processing of Primary Commodities: Effects of Developed-Country Tariff Escalation and Developing-Country Export Taxes." Journal of Political Economy, vol. 87, no. 3, 1979, pp. 559--577. JSTOR, www.jstor.org/stable/1832023.

-   Abstract: "Both DC (developed country) tariffs and LDC (developing country) export taxes are "escalated" to protect local processors of primary commodities. The paper develops an analytical model of north-south commodity trade which is used to estimate the effects of reciprocal elimination of these trade barriers for eight commodities. It is estimated that processing would increase by 9 percent in the LDCs and decline by less than 1 percent in the DCs. The LDC export revenue for the eight-commodity sample would increase by 11 percent, or just over \$1 billion (based on 1973 trade flows), which is considerably more than the estimated effect of the Generalized System of Preferences."
-   <https://www.jstor.org/stable/1832023>

17. Kreinin, Mordechai E. "The Effect of Exchange Rate Changes on the Prices and Volume of Foreign Trade (L'effet Des Modifications Du Taux De Change Sur Les Prix Et Le Volume Du Commerce Extérieur) (El Efecto De Las Variaciiones Del Tipo De Cambio Sobre Los Precios y El Volumen Del Comercio Exterior)." Staff Papers (International Monetary Fund), vol. 24, no. 2, 1977, pp. 297--329. JSTOR, www.jstor.org/stable/3866575.

-   ABSTRACT: "This paper utilizes the exchange rate experience of the Smithsonian Agreement period to investigate the effect of exchange rate changes on the prices of traded goods and on trade flows of the United States, Canada, Japan, and several Western European countries. In contrast to econometric investigations of the same topic, this study employs the control country approach to isolate the effect of exchange rate adjustments from the effects of other factors on the prices and volumes of traded goods. This approach necessitates the use of percentage changes (from 1970 to 1972, and from 1970 to 1973) in bilateral exchange rates and bilateral trade flows between the country under study and each of its main trading partners. For each of the seven countries studied, the results include (1) an estimated pass-through effect of the exchange rate on imports and exports; (2) an estimated effect on the volume of imports and exports; (3) the change in the terms of trade; (4) the implied elasticities of demand for imports and of foreign demand for the country's exports; and (5) the estimated elasticity of substitution in its market between third country suppliers for price changes occurring between 1970 and 1972, and between 1970 and 1973. The results conform well to theoretical expectations. Where comparisons are possible, they are consistent with estimates obtained by other methods. The computations yielded (at an intermediate stage) estimates of the degree of trade overlap among exporting and importing countries. Although trade overlap is not related to the subjects covered in this article, these results may prove useful to other investigators (for example, in developing or testing theories of the commodity composition of trade); they are presented in the Appendix."
-   <https://www.jstor.org/stable/3866575>
-   Comment: origional paper is in Spanish, this is a translated version.

18. Edward E. Leamer, James Levinsohn, Chapter 26 "International trade theory: The evidence, Handbook of International Economics", Elsevier, Volume 3,1995, Pages 1339-1394, ISSN 1573-4404, ISBN 9780444815477,

-   Publisher Summary: "This chapter focuses on the international trade theory. It discusses the Ricardian and the Ricardo--Viner models. These models point to technological differences as the source of international comparative advantage. A simple Ricardian model has one input, labor, which is assumed to be mobile across the two sectors of the economy, but internationally immobile. The Ricardo--Viner model introduces into the model two additional factors that are sector-specific. This gives curvature to the production possibilities curve and also allows international commerce to affect the distribution of income. Although there is little or no direct empirical support for these simple models, there is nonetheless growing awareness that technological differences are a natural consequence of economic isolation and play a role in the integration process, following an economic liberalization. The chapter provides an overview of the Heckscher--Ohlin model and discusses the Rybcyzinski theorem and the Stolper--Samuelson theorem. It also reviews the studies of the Heckscher--Ohlin model based on cross country comparisons."
-   [https://doi.org/10.1016/S1573-4404(05)80006-1](https://doi.org/10.1016/S1573-4404(05)80006-1){.uri}.

19. Bergstrand, Jeffrey H. "The Gravity Equation in International Trade: Some Microeconomic Foundations and Empirical Evidence." The Review of Economics and Statistics, vol. 67, no. 3, 1985, pp. 474--481. JSTOR, www.jstor.org/stable/1925976.

-   ABSTRACT:"Despite the gravity equations' empirical successes in "explaining" trade flows, the model's predictive potential has been inhibited by an absence of strong theoretical foundations. A general equilibrium world trade model is presented from which a gravity equation is derived by making certain assumptions, including perfect international product substitutability. If, however, trade flows are differentiated by origin as evidence suggests, the typical gravity equation is misspecified, omitting certain price variables. The last section presents empirical evidence supporting the notion that the gravity equation is a reduced form from a partial equilibrium subsystem of a general equilibrium model with nationally differentiated products."
-   <https://doi.org/10.2307/1925976>

20. Chenery, Hollis B., and Lance Taylor. "Development Patterns: Among Countries and Over Time." The Review of Economics and Statistics, vol. 50, no. 4, 1968, pp. 391--416. JSTOR, www.jstor.org/stable/1926806.

-   Intro: "GNERALIZATIONS about economic development have two main sources: historical studies of advanced countries and com- parisons among countries at different income levels. The third possibility -time-series for underdeveloped countries has proved less promising because of limited data and the past stagnation of many countries. Since each source presents serious econometric difficulties, they will provide a better basis for testing development theories if they can be used in combination. This paper brings together evidence from all three sources to test the hypothesis that there are uniform patterns of change in the structure of production as income levels rise. Simon Kuznets, the pioneer in this field, was originally impressed with the similarities between historical and cross-country patterns, but recently he has become much more sceptical.1 We will therefore apply more formal econometric methods to determine the relative importance of the factors leading to uniformity and those leading to diversity among countries. This study consists of three parts: (I) re- estimation of multiple regressions describing intercountry growth patterns for major sectors and country groups, which provide a more satisfactory treatment of the effects of differences in income level, scale and trade patterns; (II) comparison of postwar changes in each group of countries to the intercountry regressions and to the historical patterns of the advanced countries; (III) analysis of twelve industry sectors designed to provide a disaggregated view of production patterns.
-   <https://doi.org/10.2307/1926806>

21. Chipman, John "Towards the Construction of an Optimal Aggregative Model of International Trade: West Germany, 1963-1975" A chapter in *Annals of Economic and Social Measurement*, Volume 6, number 5, 1977, pp 535-554 from National Bureau of Economic Research, Inc

-   Abstract: "A mapping from international to domestic prices from Samuelson's 1953 model of international trade is fitted to German data. A method and a search procedure are described fro constructing an aggregative, lower-dimensional, model for which an approximately declined measure of aggregation bias is acceptably small, and portions of the set of internationally traded commodities are obtained which fulfill this curriculum fro purpose of explianing the respective domestic price indices, one at a time. It is ?? that the optimal number of explanatory variable import and export price index lives somewhere between 6 and 9" (some parts are hard to read)
-   <http://www.nber.org/chapters/c10542.pdf>

22. Alan V. Deardorff, *Testing trade theories and predicting trade flows*,Chapter 10, Handbook of International Economics, Elsevier, Volume 1, 1984, Pages 467-517, ISSN 1573-4404, ISBN 9780444867926,

-   Publisher Summary: "The major obstacle to the testing of trade theories has been the difficulty of constructing tests that is theoretically sound. The intuitive content of most trade theories is quite simple and straightforward. But empirical tests of the theories are often faulted on the grounds that they test propositions that do not derive rigorously from the theories. The problem seems to lie in the theories themselves, which are seldom stated in forms that are compatible with the real world complexities that empirical research cannot escape. This chapter discusses the problems that arise in testing trade theories independent of the theory being tested. To the extent that many of the specific explanations of trade have a common foundation in the theory of comparative advantage, they also share some of the same empirical complications, and it is useful to look at these before becoming immersed in the particular problems that arise from specific theories. The chapter reviews the empirical tests and implementations of the Ricardian theory, the Heckscher--Ohlin theory, and the technology theory. The chapter also reviews an assortment of other approaches to trade. These include both recently articulated theories that have not yet been tested, such as the monopolistic competition model, and empirical tests that have been done without benefit of theory, such as the so-called gravity models."
-   [https://doi.org/10.1016/S1573-4404(84)01013-3](https://doi.org/10.1016/S1573-4404(84)01013-3){.uri}

23. Harrigan, James. "The Volume of Trade in Differentiated Intermediate Goods: Theory and Evidence." The Review of Economics and Statistics, vol. 77, no. 2, 1995, pp. 283--293. JSTOR, www.jstor.org/stable/2109865.

-   ABSTRACT: "The paper develops a model of trade in differentiated intermediate goods, and shows how the structure of the importing country's production will influence gross bilateral import volumes. A regression equation directly implied by the model is estimated using disaggregated bilateral trade data for the OECD countries in 1985. The data reject the model. A more general model suggested by the theory establishes strong links between a country's factor endowments and its gross trade volume. This model is dominated statistically by a fixed effects model, and does not substantially alter the conclusions of earlier empirical studies about openness to trade in manufactured goods."
-   <https://doi.org/10.2307/2109865>

24. Helpman, Ethan "Imperfect Competition and International Trade: Evidence from fourteen Industrial Countries". *Journal of the Japanese and International Economies*, Volume I, 62-81. 1987. Department of Economics, Tel Aviv University.

-   Abstract: "Three hypotheses that emerge from a theoretical model are discussed. Two of them concern the behavior of the share of intraindustry trade while the third concerns the volume of trade. One is that in cross-country comparisons the larger the similarity in factor composition, the larger the share of intraindustry trade. The second is that in time series data the more similar the factor composition of a group of countries becomes over time, the larger the share of intraindustry trade within the group. The third is that changes over time in relative country size can explain the rising trade-income ratio. All three hypotheses are consistent with the data. J. Japan. Int. Econ., March 1987, 1(1), pp. 62--81. Department of Economics, Tel Aviv University, Ramat-Aviv, Tel Aviv 69978, Israel."
-   [https://doi.org/10.1016/0889-1583(87)90027-X](https://doi.org/10.1016/0889-1583(87)90027-X){.uri}

25. Paul Krugman, 1992. "Geography and Trade," MIT Press Books, The MIT Press, edition 1, volume 1, number 0262610868, December.

-   intro: "I have spent my whole professional life as an international economist thinking andwriting about economic geography, without being aware of it," begins Paul Krugman in the readableand anecdotal style that has become a hallmark of his writings. Krugman observes that his ownshortcomings in ignoring economic geography have been shared by many professional economists,primarily because of the lack of explanatory models. In Geography and Trade he provides astimulating synthesis of ideas in the literature and describes new models for implementing a studyof economic geography that could change the nature of the field.Economic theory usually assumes awaydistance. Krugman argues that it is time to put it back - that the location of production in spaceis a key issue both within and between nations.Paul Krugman is Professor of Economics at theMassachusetts Institute of Technology. He has been a consultant to the International Monetary Fund,the World Bank, the United Nations, the Trilateral Commission, and the U.S. State Department. He isa member of the Group of Thirty. His books include the recent bestselling Age of DiminishedExpectations: U.S. Economic Policy in the 1990s."

Comment: This is a book, I would skip to the chapter called "some imperical evidence"

26. Stern, R. M., Francis, J. H. and Schumacher, B., 'Price Elasticities in International Trade: A Compilation and Annotated Bibliography', Seminar Discussion Paper No. 62 (Ann Arbor, Department of Economics, University of Michigan, 1975).

-   Abstract of chapter 1: Abstract Estimates of the response of imports and exports to price changes are interesting and important for a variety of purposes. On an aggregate level, the investigator or policy maker may wish to know what effects exchange-rate realignments may have on the trade balances of different countries. Or, put differently, the problem may be to determine the exchange-rate change required to eliminate a trade imbalance of a given size. Exchange-rate changes will also affect aggregate income and employment as a consequence of the expenditure shifts that occur and that result in the expansion or contraction of a country's export and import-competing industries. To cope with issues like these, information on the relevant elasticities of demand and supply is necessary.
-   DOI: 10.1007/978-1-349-03137-5
-   Comment: Another Book, I only looked at chapter 1

27. PARZYCH, KENNETH M. An Analysis Of Export Trade Under The Webb-pomerene Act Of 1918, University of Connecticut, Ann Arbor, 1970. ProQuest, <https://libezproxy.syr.edu/login?url=https://www.proquest.com/dissertations-theses/analysis-export-trade-under-webb-pomerene-act/docview/302515727/se-2?accountid=14214>.

-   intro: "This study is concerned with an examination and evaluation of the importance and impact of the WebbPomerene Export Trade Act of 1918. The Act is representative of a unique position in the application of the nation's established antitrust policy to domestic business participation in international commerce. In an attempt to enhance the export capabilities of the nation's comparatively small manufacturers, the legislation provides legal exemptions from some provisions of the Sherman and Clayton Antitrust Laws for firms who aspire to coordinate their export sales program. The legislative intent of the Webb Act was to enable the relatively small export-oriented firms to realize sufficient cost-reducing and trade-creating benefits from association participation as a means of intensifying their international competitive position. As aresult, such monopolistic practices as the imposition of common export sales terms, the market allocation of export business among the participating member companies, and the establishment of export price maintenance policies, have become acceptable policy functions of the registered WebbPomerene trade associations.
-   <https://www.proquest.com/docview/302515727?pq-origsite=gscholar&fromopenview=true>

28. KIM, DAL H. An Analysis Of Shares In Korea's Import Market, 1960-1973, University of Hawai'i at Manoa, Ann Arbor, 1976. ProQuest, <https://libezproxy.syr.edu/login?url=https://www.proquest.com/dissertations-theses/analysis-shares-koreas-import-market-1960-1973/docview/302801401/se-2?accountid=14214>.

-   Abtract: While the growth performance of the Korean economy over the two decades, 1953-1973, was impressive, a continuing problem has been a large trade deficit and corresponding heavy dependence on external resources. This suggests the importance of looking at the import side of the trade balance to see what can be learned about its role in the continuing trade deficit. This study is concerned with sources of Korea's import growth. The favorable internal environment of Korea contributed to the export expansion of developed countries in Korea's import market. However, the success of these exports to Korea depended also on other factors such as competitiveness among sources of supply, condition of loans and grants, and suppliers' credit terms. In this study, an attempt has been made to analyze the effects of demand and supply factors on the actual export expansion of the four major suppliers in Korea's import market: the United States, Japan, West Germany, and the United Kingdom.The main analytical device used was Constant-Market-Share (CMS) analysis.According to CMS analysiss, the inter-country variation in export performance can be explained by two factors, the commodity compositional effect, depending on demand factors and the competitiveness effect, depending on supply factors. The competitiveness effect seems to be the more important of the two during the period 1960-1973, Among the four countries, Japan (and also the United Kingdom to a small degree) has shown the best performance. The competitiveness effect is the major factor explaining its good export performance in total products. Breaking down the analysis to a disaggregated level, the empirical results reveal that Japan has shown better export performance in almost all groups except industrial supplies (primary) and other commodities. One can say that Japan has enjoyed positive competitiveness effects which means that Japan succeeded in capturing the higher shares in Korea's market over time. The negative competitiveness effects of other major suppliers (i.e., the United States and West Germany) reflect their failure to maintain their shares in Korea's market due to the deterioration in their realtive competitiveness. Hence, the increase in Japanese shares in Korea has been at the expense of the United States and West Germany. Owing to the importance of competitiveness in determining actual export growth to Korea, this study attempts further to examine the role of price competitiveness in determining the export expansion of individual commodities of major suppliers in Korea's market. The concept of elasticity of substitution is then employed in the analysis. The empirical results show that price competitiveness has some influence in determining the export expansion of these countries in Korea's market. We interpret the positive competitiveness effect as an indication of an improved competitive position in a given country's exports in relations to those of others. But is is very difficult to pinpoint what the competitiveness is comprised of or what it means. Obviously, the price variable is important. But other factors such as the quality and uniqueness of the goods, transport costs, the speed of delivery, after sales service, and commerical and financial ties and arrangements can also be important determinants of competitiveness. Therefore, it is quite obvious that the competitiveness of export commodities from different sources of supply is influenced by non-price as well as price factors. Considering both price and non-price factors, Japanese goods seem to be preferable. Although the Korean government attempts to control imports for the improvement of balance of payments and also to diversify the import sources, it is difficult to accomplish such tasks because Korea is still in need of imports required for economic growth and industrialization, and imports from Japan are considered to be favorable at the present time since they promise a saving in foreign exchange."
-   <https://www.proquest.com/docview/302801401?pq-origsite=gscholar&fromopenview=true>

29. FIELD, ALFRED J., JR. A Multi - Regional, Multi - Commodity Descriptive And Econometric Analysis Of World Trade, 1953-1964. (volumes I And Ii), Iowa State University, Ann Arbor, 1967. ProQuest, <https://libezproxy.syr.edu/login?url=https://www.proquest.com/dissertations-theses/multi-regional-commodity-descriptive-econometric/docview/288305718/se-2?accountid=14214>.

-   Intro: "International economic relations constitute a vital and often explosive element of current domestic and international economic questions. At a time when the entire world is in the process of rapid transformation, the importance of successful international relations is paramount. The coexistence of the developed regions of the world with the developing countries in Asia, Africa, and Latin America provides a basis for political and economic tensions which can only be overcome if the needs of those larger portions of the world population can be met. The gap between developed and less- developed countries has been growing, adding further to international tensions. The problem of underdeveloped is continually affected by the low price levels and economic instability in the markets for primary products. This instability is basically the result of the sensitivity of these products to cyclical fluctuations in income and output of the industrial countries and to the disturbance which often arise from "shortsightedness of national policy makers in international trade" (163,8).1 Supplementing these sources of instability are disturbances emanating from changes in the supply situation which are often the result of the non-controllable factors of nature.1 Restrictions on imports and become more common as a number of the developing countries have taken defensive actions to inhibit the expansion of the import trade.2 The multiple problems of the less-developed countries have been accompanied by concomitant balance-of-payments problems in the developed countries of the world. These developing nations in the international trade field have been given increased attention within the framework of the General Agreement on Tariffs and Trade (G.A.T.T.), foreign aid programs, the international Monetary Fund, and recently by the United Nations Conference on Trade and Development. In addition to the work of the international agencies, a major trade promoting effect has been attempted through the kennedy round of tariff negotiations under the authroity of the United States Trade expansion Act of 1962. The major aims of these programs have been to help sustain the current high rates of growth of international trade and the expansion of the export earning of the developed counties. The effectiveness of government programs and policy decisions in international trade is heavily dependent upon an accurate understanding and evaluation of international markets on which the level and pattern of fo reign trade depend. Thus there exists a strong case for rigorous investigation in to the trends in commodity composition and geographical concentration of world trade where sufficient statistical material is available . An accurate in sight as to what governs the size and composition of imports and exports is essential to farsighted policy decisions. An exam ination of the a vailable statistics showed a noticeable lack in a consistent multi-regional, multi-commodity time series presentation of international trade data necessary for such an analys is. It appeared extremely desirable to develop a matrix o f world trade flows for the1950's and 1960's within which the relative changes in world trade could be examined, and which could be extended each year as new data became available . Consequently, the preparation of such a trade matrix was undertaken."
-   <https://www.proquest.com/docview/288305718?pq-origsite=gscholar&fromopenview=true>
