---
title: "Lit Review (non-us)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lit Review (Non-US)

1.  Stephen A. Resnick, Edwin M. Truman,"An empirical examination of bilateral trade in Western Europe" Journal of International Economics, Volume 3, Issue 4, 1973, Pages 305-335, ISSN 0022-1996,

-   intro: This paper presents an econometric model of bilateral trade flows for ten !Vest European countries from 1953 to 1968. Our aim is to develop and estimate a trade model which yields a reasonable set of direct and indirect price effects while endeavoring to avoid the problem of multicollinearity of price. The structure and estimates of such a model allow us to explore the implications of differential price changes or discriminatory tariff changes for the trade of the countries included in the model. A second paper by the authors (Resnick and Truman, 1973) presents these policy results. If the model were expanded to include at least the United States, Canada and Japan as separate importers and sources of supply, it might be useful in analy; ing the effects of exchange rate changes.
- Notes: The model used in this article looks at imported goods to caluclate price elasticities of the demand for imports from the 10 west European countries (pg 306). The pricipal data sources are from the interantional Monetary Fund, Political and Economic planning (1962 & 1959), and United Nations Commodity and trade statistics.
-   [https://doi.org/10.1016/0022-1996(73)90025-1](https://doi.org/10.1016/0022-1996(73)90025-1){.uri}.

2.  Officer, Lawrence H., and Jules R. Hurtubise. "Price Effects on the Kennedy Round on Canadian Trade." The Review of Economics and Statistics, vol. 51, no. 3, 1969, pp. 320--333. JSTOR, www.jstor.org/stable/1926566.

-   "CANADA was one of 52 countries participating in the "Kennedy Round" negotiations of 1964-1967. Because of the openness of the Canadian economy, the potential results of these trade liberalizations on its imports and exports are of special interest.' In this study we forecast the price effects of the Kennedy Round on Canada's trade as of 1973, when all the negotiated tariff reductions are scheduled to have occurred. We consider the impacts on total Canadian imports and exports to the United States, and analyze them disaggrega- tively by commodity groups. This is done by means of a four-stage procedure: 1) Develop time series of trade, price, and activity that are useful, indeed essential, for any systematic examination of Canadian trade.2 2) Estimate demand functions for Canadian imports and exports, using as data the series obtained in (1). 3) Construct tariff rates for the commodity groups in (2) on pre-Kennedy (pre-1968) and post-Kennedy (post-1972) bases. 4) Deduce the price effects of the Kennedy Round by the application of the tariff rates in (3) to the demand functions in (2). In section II we discuss the specification and estimation of the demand functions. We present estimated equations for Canadian imports in section III and for exports to the United States in section IV. These equations and some especially constructed data are applied to calculate the effects of the Kennedy Round in section V."
-   Notes: Includes data on the US demand for Canadian Exports. But beyond that this only talks about Canada so I moved it to the non-US list.

7.  Pöyhönen, Pentti. "A Tentative Model for the Volume of Trade between Countries." Weltwirtschaftliches Archiv, vol. 90, 1963, pp. 93--100. JSTOR, www.jstor.org/stable/40436776.

-   " Contents: I. A General Model for the Structure of the International Exchange of Goods. - II. Finding the Form of the Explanatory Model. - III. The Data Used. - IV. Estimation of the Parameters of the Model. - V. On the Values of the Parameters. - VI. Discussion of the Results. paper aims to bring some structural features of international trade into relief. The analysis is based on the simultaneous appli- cation of a structural and explanatory model resembling an input- output model to the exchange of goods between ten European countries in 1958. The nature of the experiment made it necessary to confine the analysis at this stage to a relatively limited set of data, but there is nothing, in principle, to prevent the extension of the analysis to the world trade as a whole. Changes over time were also left outside the scope of this paper, so that the model employed is static. In spite of these restrictions the results are of interest and, as I believe, novel; they serve to indicate that the bilateral approach can be abandoned in investigating international trade, which can be treated as an integral whole within the framework of a single model or model system."
- Notes: Uses 10 European Countries: Belgium, Denmark, Finland, Western Germany, Italy, Netherlands, Norway, Portugal, Sweden, and UK.



*NEW ENTRIES* 



3. Helleiner, G.K. "The Political Economy of Canada's Tariff Structure: An Alternative Model." The Canadian Journal of Economics / Revue Canadienne D'Economique, vol. 10, no. 2, 1977, pp. 318--326. JSTOR, www.jstor.org/stable/134449.

-   "Caves's recent imaginative attempt to test models of the process of Canadian tariff policy formation (Caves, 1976) concluded that an interest group approach had greater explanatory power than the alternatives he tested. His particular specification of such a model, however, is by no means the only plausible one. Indeed, Caves himself notes the many qualifications to which his results are subject. This paper tests an alternative interest group explana- tion of the Canadian tariff structure. The model differs from that of Caves in two major respects. In the first place it attempts to take certain international political influences into account as well as the purely Canadian ones. Secondly, it focuses upon a different set of explanatory variables from Caves's model even as far as domestic influences are concerned. Caves's analysis attempted to explain no more than the pattern of Canadian tariffs in a single year, 1963, since which there have been significant tariff changes. New data now available make it possible not only to update such studies of the Canadian tariff but also to analyse recent changes therein (Wil- kinson and Norrie, 1975)."

4. Chipman, John "Towards the Construction of an Optimal Aggregative Model of International Trade: West Germany, 1963-1975" A chapter in *Annals of Economic and Social Measurement*, Volume 6, number 5, 1977, pp 535-554 from National Bureau of Economic Research, Inc

-   Abstract: "A mapping from international to domestic prices from Samuelson's 1953 model of international trade is fitted to German data. A method and a search procedure are described fro constructing an aggregative, lower-dimensional, model for which an approximately declined measure of aggregation bias is acceptably small, and portions of the set of internationally traded commodities are obtained which fulfill this curriculum fro purpose of explianing the respective domestic price indices, one at a time. It is ?? that the optimal number of explanatory variable import and export price index lives somewhere between 6 and 9" (some parts are hard to read)
-   <http://www.nber.org/chapters/c10542.pdf>

5. KIM, DAL H. An Analysis Of Shares In Korea's Import Market, 1960-1973, University of Hawai'i at Manoa, Ann Arbor, 1976. ProQuest, <https://libezproxy.syr.edu/login?url=https://www.proquest.com/dissertations-theses/analysis-shares-koreas-import-market-1960-1973/docview/302801401/se-2?accountid=14214>.

-   Abtract: While the growth performance of the Korean economy over the two decades, 1953-1973, was impressive, a continuing problem has been a large trade deficit and corresponding heavy dependence on external resources. This suggests the importance of looking at the import side of the trade balance to see what can be learned about its role in the continuing trade deficit. This study is concerned with sources of Korea's import growth. The favorable internal environment of Korea contributed to the export expansion of developed countries in Korea's import market. However, the success of these exports to Korea depended also on other factors such as competitiveness among sources of supply, condition of loans and grants, and suppliers' credit terms. In this study, an attempt has been made to analyze the effects of demand and supply factors on the actual export expansion of the four major suppliers in Korea's import market: the United States, Japan, West Germany, and the United Kingdom.The main analytical device used was Constant-Market-Share (CMS) analysis.According to CMS analysiss, the inter-country variation in export performance can be explained by two factors, the commodity compositional effect, depending on demand factors and the competitiveness effect, depending on supply factors. The competitiveness effect seems to be the more important of the two during the period 1960-1973, Among the four countries, Japan (and also the United Kingdom to a small degree) has shown the best performance. The competitiveness effect is the major factor explaining its good export performance in total products. Breaking down the analysis to a disaggregated level, the empirical results reveal that Japan has shown better export performance in almost all groups except industrial supplies (primary) and other commodities. One can say that Japan has enjoyed positive competitiveness effects which means that Japan succeeded in capturing the higher shares in Korea's market over time. The negative competitiveness effects of other major suppliers (i.e., the United States and West Germany) reflect their failure to maintain their shares in Korea's market due to the deterioration in their realtive competitiveness. Hence, the increase in Japanese shares in Korea has been at the expense of the United States and West Germany. Owing to the importance of competitiveness in determining actual export growth to Korea, this study attempts further to examine the role of price competitiveness in determining the export expansion of individual commodities of major suppliers in Korea's market. The concept of elasticity of substitution is then employed in the analysis. The empirical results show that price competitiveness has some influence in determining the export expansion of these countries in Korea's market. We interpret the positive competitiveness effect as an indication of an improved competitive position in a given country's exports in relations to those of others. But is is very difficult to pinpoint what the competitiveness is comprised of or what it means. Obviously, the price variable is important. But other factors such as the quality and uniqueness of the goods, transport costs, the speed of delivery, after sales service, and commerical and financial ties and arrangements can also be important determinants of competitiveness. Therefore, it is quite obvious that the competitiveness of export commodities from different sources of supply is influenced by non-price as well as price factors. Considering both price and non-price factors, Japanese goods seem to be preferable. Although the Korean government attempts to control imports for the improvement of balance of payments and also to diversify the import sources, it is difficult to accomplish such tasks because Korea is still in need of imports required for economic growth and industrialization, and imports from Japan are considered to be favorable at the present time since they promise a saving in foreign exchange."