---
title: "Traders and Diplomats by Preeg"
author: "Benjamin Heyries"
date: "Wednesday, May 6, 2015"

output: word_document
---

_Traders and diplomats_ by Ernest. H. Preeg describes the negotiations during the Kennedy round. This book is particularly interesting as it is the first time that reductions across-the-board are put into practice. In this summary I will follow the chronological order privileged by the book. As a consequence, I will first focus on the difficulties to reach the general formula or tariff concession. Then, as all sectors could not be treated the same, I will present how exceptions were handled. In conclusion, I provide the principal features which may be worth considering in the frame of other negotiations.

Reaching the general agreement
===================================================


The Kennedy round is a round of change. Not only the process of negotiation is drastically changed but Agriculture is added to the list of concessions as a major issue, the GATT has to fight the new wave of particularism which spread because of the formation of new custom unions (the EEC, the EFTA) and, finally, developing countries are getting more and more importance in the GATT, changing the balance of power. The difficulties could have been dealt one by one on the long run if the limitation of the time for negotiating allowed to the US were not limited by the deadline of June, 1967, set by the Trade Expansion Act. As extension was impossible, this deadline loomed over the Contracting Parties and created pressure to conclude an agreement. They managed to agree only at the very last moment.

### Context for the major belligerents

	1. The European economic integration

The EEC created by the Treaty of Rome in 1957 was already problematic during the Dillon round in which renegotiations had to take place. However, the scope of the Kennedy round and the enthusiasm linked to it highlighted the new economic order. The EEC, like the US or the USSR, is a partner of first importance. With the EFTA and the US, they form a trio of divergent interests. Contrary to the notion of free trade area, like the EFTA, the EEC is a custom union which implies not only no barriers between members but also common external tariffs. As such, they formally negotiate together during the round (contrary to the EFTA members).
The common market had prior to the beginning of the round been labeled as a challenger of the international trade. The Chicken War of 1962 sketched the opposition that will take place between the United States and the EEC during the round. The challenge of the Kennedy round is to reduce tariff by an amount large enough to enable non-members of the EEC to compete within the Common market. Indeed, since the creation of the EEC, the United States lost a volume of 132 million dollars, the principal beneficiaries of this loss being the members of the EEC.
Meanwhile, the creation of the EFTA hurt a lot the interests of the EEC. As a consequence, its members want the Kennedy round to reduce the differential in tariffs which affect the Contracting Parties outside the free trade area. 

The decision making process of the EEC is far more complex than any other Contracting Party. Indeed, the Council of Ministers give the power to the Commission which send a delegation to Geneva. The problem is that the Council of Ministers still decides in 1963 with an absolute majority, and the French president De Gaulle is really attached to that voting process. As a consequence, the Commission has a very small margin to negotiate in Geneva. This will ultimately lead to a crisis in 1965 which endangered greatly the negotiations.

	2. The United States and the Trade Expansion Act of 1962

In the 1960s, the American economy is not as booming as it used to be. It is not a real crisis but a small recession. The first attacks against the dollar happen and the gold reserve decreases. It is necessary to avoid another Dillon round where the peril point limit the possibility of negotiating. The presence of a bold president could overcome this issue. The Trade Expansion Act was necessary to avoid the former item-by-item negotiations, which limits the scope of the agreement and increases tensions between the Contracting Parties. 
The Trade Expansion Act sets the frame of the negotiation: the President has the authority to cut by 50% the tariff which are more than 5% and suppress the one lower than 5%. This authority only last for 5 years. Some exception are included in the deal: an escape clause is introduced as well as a different treatment for products deemed as essential for national security.
The reactions toward the TEA were mixed. The EEC was glad to be able to negotiate but some dark clouds were already above the negotiations. The issue of disparities, the fact that some countries may have actually lower base rate than others, and especially the difference between the EEC's tariffs lines, which were all around 10%, and the very heterogeneous US tariff system where high tariff rates and low tariff rates coexist, was really worrisome. It does not seems that the French and the EEC will go with the linear cut. As a consequence, the Ministerial Meeting of the Kennedy round started on a divergence on the rule to apply.

### Making offers

This is an intense period that will end by the final proposals in matter of linear cuts and specific offers. It spreads from May 1963, which is the start of the Kennedy round, to July 1965, the moment at which the tensions explode.

	1. Establishing the Rules

All Contracting parties agree on two elements. First, it is necessary to have across-the-board negotiations. Second, the disparities constitute an issue that it is necessary to handle. This is the conclusion of the ministerial meeting. As it does not specify the method for linear cut nor the way to handle disparities, it actually solves nothing.

Disparities is an important source of conflict. A first issue is the definition of a disparity. At which threshold a gap between two tariff lines is called a disparity, that is a real mystery in May 1963. The second issue worsens the first one: how to handle disparities. This is critical and the focal point of all discussion until May 1964. Indeed, disparities are a problem already mentioned in Torque and, as the Kennedy Round is the first of its type, setting things right at the start may prevent any costly change in future negotiations. Two methods are in competition. The EEC, under the pernicious influence of the French delegation, abandoned the linear cut for the method of "ecretement", which consists in a sort of tariff harmonization. They advocated that the linear cut would worsen the gap between in protection between the United States and lower-average-tariff countries like the one in the EEC. Some other arguments were raised like the relative unfairness of high tariff lines compared to lower and less objectionable duties or the strategic concerns over the impossibility of reciprocity in the next rounds. For example, as reciprocity was not defined at that time, there were some worries about a potential situation where the EEC, under the rule of reciprocity, would give up a lot a bargaining power by suppressing several low tariff lines to decrease one high tariff line of the U.S.. Moreover, the fact that the group of high tariff countries were well identified and in the spotlight compared to the rest added some unnecessary tensions in the negotiations. The different nomenclatures, especially in textile and chemicals, made the talk even harder. The problem of disparities is that there is not any good solution. The supplementary cut which would be necessary by the United States seems pretty unfair and was forbidden by the 50%-cap set by the TEA of 1962. Using the "ecretement" method and putting the concession on high-level tariff lines at 50% would reduce the scope of the agreement and inevitably harm third parties. The problem is not solved on a general basis and the future of the round depends on the specific negotiations in touchy areas.

Other negotiations issues were raised during the Round. First, it was the occasion of the empowerment of the developing countries. They had few possibilities but, as agreement need to be reach on the largest basis, their role was more important than in the previous bilateral negotiations. Another problem was non-tariff barriers, and in particular the American Selling Price (ASP), which would play an important role at the end of the round. Finally, agriculture was at the center of the US policy which was afraid of the magnitude the Common Agricultural Policy of the EEC (remember the Chicken War).

	2. Specific offers

From May 1964 to June 1965, the Contracting Parties agree on the 50% linear cut as a "working hypothesis" and prepare exemption lists. The publication of the lists triggered some problems which contributed to an eight-month interruption of the negotiations.
Disparities led to the proposition of exemption list. Most of the items contained in the list were in problematic sectors: agriculture, textile and chemicals. With the submission of the exemption list, a problem arose in the negotiations. Linear cut preserved the scope of the Round but did not help to establish a working process to handle disagreement on exemption lists. Some questions remained unanswered: how should the negotiations be completed (bilateral? truly multilateral? MFN?)? How to negotiate in sectors that considered as strategically critical? The solution was to create sector groups who would deal with the particularly burning issues.
5 industrial sector groups were created: pulp and paper; aluminum; iron and steel; cotton textiles; and chemicals. Pulp and paper disagreement lied between the EEC and the Nordic countries. The discussions were a success. For aluminum, several actors had substantial interest. The explosion of the use of the metal made it harder to conclude an agreement even with the support of the private actors. The outcomes of the negotiation were not really satisfying. The sector group failed to suppress the barriers it had been appointed for, in particular the EEC's quantitate restrictions. The negotiations for iron and steel were also difficult. Only a major concession of the UK to the ECSC saved the day in the very last months of the round. Cotton textile agreement was a clear disappointment for exporting countries. Even if tariffs were down by 20%, the fact that they were not bound to this level (they could "snap-back" if the long-term arrangement was interrupted for some period) reduced the scope of the concessions. Chemicals triggered the crisis in the EEC. The American Selling Price (ASP) and the high disparities in the sector tied the hands of American delegation and particularly upset the UK and the EEC. Indeed, chemicals were taxed under a non-traditional tariff system. As the TEA only gave the President the right to negotiate tariff lines, the negotiation on product for which the ASP was used as a benchmark was forbidden. As most of the disparities were in this category, the other delegations found the proposition of the United States unacceptable. 
Agriculture was negotiated separately from industrial product. No cross-sector reciprocity could be done with industrial products.

The political crisis that struck the EEC in 1965 is not directly linked to the Kennedy Round. However, the issues previously raised may have worsen the situation. Even if the Kennedy round is not directly related to it, the crisis deeply influenced the negotiations.

Going through the EEC crisis and reaching an agreement
===================================================

The crisis stems from a trial to reform the EEC working process. Indeed, one of the fundamental innovations was to give to the Parliament some kind of power (rather than only consultative one). The negotiations in Geneva were explicitly mentioned to justify the move.
As France objected, the negotiations stopped in Geneva. No agreement had been reached and therefore the EEC delegation has no power to negotiate. As the EEC was one of the major player in the negotiations, it has the effect of stopping the progress of the negotiations, each Contracting Party waiting for the return of the EEC. Side problems were tackled and sector groups pursued their analysis of the situation. However, no breakthrough could be achieved without the EEC. The Contracting Parties themselves had to wait for an improvement of the situation. The United States moved ahead on subsidiary topics. However, the continuous French rebuff, also known as the policy of the "chaise-vide", limited the effects of this initiative. 
Negotiating without the EEC would considerably reduce the scope of the agreement and the Kennedy round appeared to be really disappointing during that period. No real alternative could be found to the European participation. 
The Deadlock ended when the French and the other members of the EEC agreed on the impossibility to currently solve the problem.

### Negotiations resume

The EEC crisis implied that the Contracting Parties only have a year and a half to conclude the negotiations. At that point, no concession has been agreed on and a lot needed to be done in the matter of exemptions. Some features facilitated the conclusion of the negotiations: the Nordic countries gathered to negotiate under the delegation of Sweden; the US deadline of June 30 1967 forced the Contracting Parties to accept offers; and no reciprocity was expected from developing countries (which simplified the negotiations and reduce the size of the necessary consensus). In 1966, four issues were at stake: concluding the nascent negotiations in the sector groups; establishing EEC disparity claim (the previous list was not precise enough, especially in partial concessions); the status of agriculture as a non-compensatory sector for industrial concessions (no reciprocity can be based on the exchange on an agricultural concession and an industrial concession); improvement of bilateral offers, the exemption lists from Canada and Japan appearing as unacceptable. As usual in the GATT, measuring reciprocity added itself to the particular problems. The factors which were agreed on to measure reciprocity are many: depth of the concession, trade volume, and loss of duties collectible (import * absolute tariff concession), projected trade impact (based on elasticities). The massive employment of statistics helped to confine the issues to a small number. 

The offers were not considered as satisfactory by any Contacting Party. The United States found the EEC too mild on agriculture. The EEC was hurt that its efforts had not been noticed by the US. One of the problem in the Kennedy-type of negotiation is that withdrawal from a Contracting Party can trigger a chain of withdrawals from the others and therefore reduce the scope of the round. Luckily, the internal disunion of the EEC prevented any possibility of withdrawing the list they submitted. As a consequence, they did not appear as a threat to the negotiation and fostered concessions from other delegations. 

Agriculture stands out as a particular issue. It was at the center of the round as the EEC was developing an aggressive CAP whereas the United States, like usual, was looking for new markets into which to expand to avoid over-supply in the markets it currently supplied. The USA and the EEC each fought to preserve its own domestic production. Moreover, negotiations in agriculture cannot rely on previous experience, like for industrial products. Indeed, agriculture has been excluded from the previous rounds. Finally, agricultural trade is different from trade in industrial products as countries are not both exporters and importers. Unlike in industrial product where countries who makes concessions benefit by reciprocal concessions in the same sector, agriculture tends to be a polarized market, fostering imbalance. Following unsatisfactory initial offers, the United States waited for the EEC to match its requirements. From this strategy some success resulted. Particular issue were critical. Frist, grain was complicated by the fact that even inside the EEC the price were hard to settle. Three topics were settled: international price, which were too low for the EEC while the US was struggling to keep it low; the food aid program, which was problematic for third countries as well as in its implementation; the access to foreign market, as the EEC was building up barriers thanks to a variable levy. The two first problems were solved whereas the Contracting Parties failed to agree on the third one. 

### Finalizing the agreement

January 1967: it is absolutely necessary to conclude because of the deadline in the U.S.. Contracting Parties were not out of trouble as public opinion was losing faith in the success of the Kennedy round; ferocious opposition in the United States took the Kennedy round as the symbol of poor international policy; and conflicts appeared as the UK was kept out of the EEC again. The disenchanted were fostered by other trade issue as the coming conference of UNCTAD. However, the last six month of the conference, even if it had its bumps, also led to major achievements: the antidumping agreement and the conclusion of the industry sector negotiations. Problems were encountered in the Chemical sector group. The American Selling Price, and the impossibility to negotiate on it, upset a lot the trading partners. The small fraction of the high duty products prevent any possibility of agreement.

In March 1967, there was still a lot to do. The offers were specified, renegotiated and accepted by all the major trade partners. The agreement was reached and, if some outcomes were disappointing, total failure was avoided.
