---
title: "Tariff Negotiations and renegotiations under the GATT and the WTO by Hoda"
author: "Benjamin Heyries"
date: "Wednesday, May 6, 2015"
output: word_document
---

_Tariff Negotiations and renegotiations under the GATT and the WTO_ by A. Hoda describes the procedures under which tariff lines are negotiated. Contrary to the previous books I read for the study, it is not a history book which related the different phases of a certain round or the evolution of the practices but rather a guide for a student in international law.
In this summary, I try to make a list of the relevant elements that play a crucial role in the establishment of the negotiations. Then, I construct a chronology which describes the establishment of a tariff schedule for a country C.

Some Rules to negotiate
===================================================

### The procedures in the multilateral tariff conferences

	1. Overview 

By multilateral conference, I refer to the round of negotiation in which members of the GATT negotiate altogether some tariff concessions to each other. There are Geneva I, Annecy, Torquay, Geneva II (even if was started a plurilateral supplementary negotiation), Dillon, Kennedy, Tokyo and Uruguay rounds. The participation vary in the different rounds. Until Kennedy, it is not mandatory to participate in the first rounds. However, in order to benefit from concessions made by their trade partners, nations usually decide to get in the round at least to establish a dialogue with  the other contracting parties. The composition of the rounds is the following:

  * Geneva: 23 original members. China left after the change of regime; the major issue was to form a temporary but efficient structure that would start the work of the ITO before it actually exists.
  * Annecy; to the original members, 11 more take part in the negotiations. Only 9 (Denmark, Dominican Republic, Finland, Greece, Haiti, Italy, Nicaragua, Sweden and Uruguay) access finally to the GATT membership after completion of the round. Tariff was the major concern.
  * Torquay: 6 more countries negotiate with the contracting parties. 4 access to the status of membership (Austria, Federal Republic of Germany, Peru and Turkey). Even if they concluded agreements with the contacting parties, Korea and the Philippines do not access to the GATT before completion of another round. As in Annecy, tariffs were the major concern. It only targeted industrial product.
  * Geneva II: it is an exception within the group of rounds. As its legal status is actually the one of a plurilateral round of negotiations joining the round is far from automatic. Only 25 out the 39 contracting parties participated in 1956 to the negotiations. As the major trade partners participated, the reduced participation did not really represent an issue. The entry of Japan and tariffs negotiations were the two principal topics of the talks.
  * Dillon: it focused on the new formation of the EEC and the renegotiation of tariff under the custom union. 
  * Kennedy: introduction of across-the-board tariff reductions and some non-tariff barriers. The anti-dumping agreement and some breakthrough in agriculture are also results of the round. Participation is also made mandatory.
  * Tokyo: negotiations of the non-tariff barriers were at the heart of the round. The GATT also confirmed its global dimension as more and more Third-World countries are joining the negotiations and being active in it.
  * Uruguay: the round enlarge the negotiations to services and intellectual property, goods losing some of the focus. Success in agriculture was made possible by industrial negotiations. 

	2. Modalities of tariff negotiations

The modalities of the negotiations evolve with the deepening of the process. As a consequence, it is necessary to separate the description of the modalities of negotiation in different periods.
The different criteria which condition the negotiations are the manner of exchange of concessions and the rules attached to the global agreement and the exception to it.

During the first three rounds and Geneva II, the Contracting Parties exchanged concession on a product-by-product basis. This reduces considerably the scope of the negotiation as the concession must be an actual notification of a new tariff line level. Most of the negotiations were held bilaterally. Even if side negotiations influenced the process, this influence was more indirect than contained in the procedures. The government are perfectly flexible on the offers they make. For example, there may be some cases where binding allows the contracting parties to set the tariff "concession" at a higher level than it actually is. The idea of negotiations "across-the-board" where Contracting Parties agree to cut the overall tariff lines by a certain percentage was already present in the early round. Torquay and Geneva II made some move toward it: Torquay mentioned the idea and Geneva II regularized the renegotiation process. However, the first time the process was actually employed was in the Dillon round and it was popularized by the success of the Kennedy round. 
Another feature that should be taken into consideration before detailing the rules is the regulation regarding Contracting Parties' participation. Participation is not mandatory until the Kennedy round. If in the first three rounds, most of the Contracting Parties participate, the  failure of Geneva II to gather all the GATT members as well as the increase share of developing countries made participation a big issue. Mandatory involvement evolved from the Kennedy round where countries had to participate but did not have to make concessions (for the developing countries, see the paragraph on reciprocity), to the Tokyo round, where some concessions were requested, to the Uruguay round where each Contracting Party had to provide a schedule of concessions.

The negotiations are conditioned by some rules that are explicitly mentioned. 

  * The most important one is reciprocity. It is the concept that concessions are made only on the basis of an "adequate concession in return". Like some other points of the GATT legislation, the notion of reciprocity was not defined in precise terms, nor were there any indicated procedures to measure it. Until Kennedy and Tokyo, this difficulty was overcome by the progressive harmonization of the tariff lines. Reciprocity is still an unsolved problem as the quantification of non-tariff barriers further complicates the application of the rule. A point worth mentioning is the different application of the rule according to the status of the Contracting Parties. This principle does not hold for Contracting Parties deemed as too weak to make important concession. In fact, most of the developing countries were exempt from the requirement of reciprocity until the Kennedy round, where concessions were made upon suggestion, and the Tokyo round, where some concessions had to be made. This infringement of reciprocity is further reduced during the Uruguay round when the developing countries were asked to make some substantial concessions.
  * Besides reciprocity, another important rule is the principal supplier rule. A contracting party can only participate in the negotiation of an item if it has a principal interest or a substantial interest in the trade of the product. There is an important difference between the two statuses. A principal supplier status implies that any modification of a tariff schedule must have the agreement of the principal supplier. On the contrary, in the case of a substantial interest, a simple consultation is necessary.
  * Some other rules play a more specific but still important role. First, the government are absolutely free to propose any concessions. The level of concession is up to the Contracting Party. In the case of across-the-board tariff cuts it can lead to major complications as consensus is needed to make any tariff concessions. Then, it can lead to awkward situation where the tariff proposed is actually higher than the applied tariff. Such practices are possible because of a rule that stipulate that binding a low tariff line is actually equivalent to the concession of a high tariff line.
  * Finally, negotiations are made under different status. It can be done under Most-Favored-Nation or over a non-contractual preferential status (like the GSP). This preferential rates apply mostly to the Commonwealth and the French colonies which are progressively phased out with the appearance of other custom unions like the EEC or the EFTA. An important feature that regulates the spreading of preferential treatment is the fact that margins between MFN and GSP are frozen. As a consequence, any negotiation on the GSP reduces by the same proportion the MFN amount as well as any negotiations on the MFN status either decrease or phase out the GSP tariff line. Finally, if negotiations are made on both rate, the Contracting Parties involved in both negotiations has to agree on the new tariff lines. 

That is it for the rules. Their application are reported in the next section: processes.

	3. The processes of negotiation

During the first five rounds, the negotiations are done by pairs. Each Contracting Party exchanges a first list of actual custom level, then a list of intended requests of tariff concessions, a list of final requests of tariff concessions, and finally a final list of offered concessions. These documents are sent to the Secretary of the GATT in the form of consolidated lists (the documents which are reported on the WTO website). The timing is defined in the ministerial meeting which define the different deadlines for each type of document. The concessions list, even if they were supposed to be secret, were also known by other participants. The Contracting Parties were thus making concessions not only on what they wanted but also on what they expected others to do. The principal supplier rule played an important role in this process. Indeed, tariff lines are only negotiated by principal suppliers, which limits the possibility to free ride on important items. Moreover, if a principal supplier were not present or willing to negotiate, the negotiation of the tariff line was postponed. This may explain why the tariff concessions in industrial products were faster than in other sectors as the early Contracting Parties were principal suppliers in that category of products. 
From the Kennedy round, the across-the-board tariff negotiations implies two things. First, negotiations took place before the list of concessions were offered. Indeed, Contracting Parties had to agree on the rate of reduction. Then, specific concessions related to pronlematic sectors, like chimecals or agriculture were analyzed as exemptions to the general concession. As it had been said earlier, the across-the-board linear cut transformed the way to negotiate. The first agreement was tougher to reach and exemption lists may ruin the previous agreement (the Kennedy round was pretty intense, see the summary on E.Preeg's book). However, the share of concessions on the overall tariff lines appeared to be very high from this process. 
The reciprocity rule was applied on different basis in the different rounds. In the bilateral agreements, most of the efforts were done on bilateral reciprocity, the two criteria taken into account being the depth of the tariff cut and the volume of trade on which the concession apply. When across-the-board linear cuts were introduced, the calculation of reciprocity became harder. The disparity problem worsened the relations between the Contracting Parties. Statistical and multiple-factor (like the existence of existence of quantitative restrictions) considerations were gathered in a complex evaluation of reciprocity.
Another important procedure to settle was to choose the rate from which concession would be offered. Like the observance of reciprocity, no general rules were stipulated and it was done on a round-by-round basis. For example, Torquay set a date at which the tariff would serve as "base rate" for concessions. In other rounds, it was the previously negotiated rates that were used. This issue can lead to conflict and a separated negotiation process. For example, during the Tokyo round, Japan and Australia used the previously negotiated rate at the GATT whereas other Contracting Parties agreed on a date at which the actual rate would be the base rate. As some liberalization occured in the first group of Countries, they found the Japanese and Australian proposition unsatisfactory. Therefore, as not base could be generally agreed on, separated negotiations were held with those countries.
Finally, it is necessary to say a word about accession. Countries acceding to the GATT have to provide a schedule. While they are not GATT members yet, they received provisional accession. However, the commitment to a schedule does not provide necessarily accession to the GATT nor to all of the advantage that are linked to that status. In the overview, I spotted some countries that actually negotiated agreements and who actually accessed the GATT only later on. Another exception is Switzerland, who was granted the right to be considered as a GATT member, and therefore it accessed to the MFN tariff lines and initial negotiating rights, even if it was not a GATT member. In some special cases, no concessions were asked to the new members. Romania and Poland did not have to provide any. Eventually, the benefits from the accession to the GATT membership can be reduced by the invocation of article XXXV by the existing Contracting Parties. It grant to the Contracting Parites the right to not apply MFN tariff lines to the new members. The article XXXV was especially used against Japan in 1956 who progressively reached the MFN status with all countries. 

### Around the multilateral conferences: special periods of negotiations

Negotiations at the GATT did not only take place in the conferences involving all Contracting Parties. In several regulated occasions, pairs or even groups of contracting parties negotiated new agreements. Moreover, renegotiations took place several time which led to the alteration of the tariff schedule of several countries. In order to avoid chaos and enable further negotiations, the GATT regulated these particular phases. In this section, I try to provide an overview of the particularities linked to each phenomena.

The first occasion in which the Contracting Parties can negotiate tariff lines outside the multilateral conference is during the bilateral or plurilateral negotiations. There were, in the whole history of GATT, only 9 occurrences (excluding Geneva II), all of them being bilateral. The Federal Republic of Germany did 7 of this type, the USA 1 and Japan 1. Except for Germany, they takes place when a special occasions: when New Zealand agrees to withdraw its appeal to article 35 for Japan and in time of civil war for Cuba and the United States. These procedures are also used during the Tokyo round in order to conclude the Agreement on Trade in Civil Aircraft. They are more important under the WTO as they reach some success in pharmaceuticals and in information technology.  
The second moment is when Contracting Parties try to renegotiate the terms of the agreement.  Renegotiations were necessary because the initial tariff commitments had a validity of only 3 years. However, as the GATT becomes more permanent, the Contracting parties adopted an automatic extension of validity of 3 years. As a consequence, every 3 years starting 1st January 1958, Contracting Parties could ask for renegotiations. Before 1958, no real procedure was available: the Contracting Parties could renegotiate under the first paragraph of article XXVIII, which was straightly compensatory, or under "sympathetic considerations". The "sympathetic consideration" motive implies that the renegotiations does not have to be strictly compensatory contrary to the normal procedure. After 1958, several procedures can be used to renegotiate: the first paragraph (like before), the 4th (which is not used anymore after the Kennedy round but it was the major way to do it) and the 5th (which became widely used in 1970). All of them were usually used to withdraw concessions in order to protect a particular industry or to extend the negotiation time at the end of a round. Usually, they consisted in the exchange of compensatory concessions to balance the withdrawal. Other renegotiations are possible, like under the article XXIV: 6 when a custom union is formed (the EEC uses it at 6, 7, 10 and 12 members and after). The other procedures involved are very rare and target very special situations (change to the harmonized system, "sympathetic considerations"...).  
The two last paragraphs deals with the modification of schedule. However, there is a practical problem linked to the modification of schedule. As each schedule is added to the protocol which ends the conference, any modification of the agreed term needs to receive the agreement of all. The first attempt to simplify this issue is the adoption in 1968 of individual certification where each Contracting Party has to notify its agreement to the rectification. However, even with this new process, some modifications were only ratified and could be applied 10 years after the conclusion of the renegotiation. Facing this issue the GATT then set a system of collective certification in 1980. After renegotiations, the Contracting Parties are notified and if within 3 months no objection is raised, the certification is adopted.

Chronology of events
===================================================

There is a chronology of event between two multilateral conferences:

  * Ministerial meeting
	* Multilateral conference
	* Renegotiations to pursue the negotiations
	* Certification if renegotiations are successful
	* Plurilateral/Bilateral supplementary negotiations
	* Renegotiations every 3 years
	* Certification if renegotiations are successful
	* Renegotiations for custom union or other extraordinary occasion
	* Ministerial meeting
	* Multilateral conference
