---
title: "results"
author: "Kristy Buzard"
date: 'last edited `r Sys.Date()` '
output: pdf_document
---

```{r,  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Large-scale tariff reductions within the framework of the General Agreement on Tariffs and Trade (GATT) have come as a result of a series of eight rounds of negotiations that began in 1947. Most of the literature that attempts to understand this phenomenon is theoretical, in large part because data availability has been a major barrier to empirical research on this massive dismantling of trade barriers.\footnote{See, for instance, the literature that seeks to explain the gradual nature of this liberalization, e.g. Devereaux (1997) and  Chisik (2003) who focus on exporters; Mussa (1986), Staiger (1995) or Mehlum (1998) on the import-competing story; or Zissimos (2007) on the role of the `withdrawal of equivalent concessions' rule.} Bown and Irwin (2017) have documented the available data, finding it to be frustratingly sparse. The data they find are applied tariffs--i.e. those that are actually charged at the border---and are disaggregated to the level of ten broad sectors at most. 

As little as we know about applied tariffs in this context, we know even less about the negotiated tariff bindings. Somewhat surprisingly, data on the tariff commitments made by the GATT signees has not been widely available, preventing empirical studies on the workings of the GATT and the dynamics of this important episode of trade liberalization.\footnote{One notable exception is Bagwell et al. (2020) who digitize the bilateral negotiation records for the Torquay Round. In order to use the bilateral data they have, one would have to digitize and combine all of a country's bilateral commitments.}

Both having more industrial detail about tariffs and having this detail be for negotiated tariffs is important. First, the negotiated tariff commitments allow us to study the political constraints that led to the GATT agreements. The negotiated tariffs are the cleanest data that exist for all negotiating parties since they are not complicated by the various processes that determine applied tariffs. Second, often the most relevant object in terms of policymaking is the gap between the negotiated tariff and the applied tariff; this is known as tariff overhang or ``water'' in the bindings.\footnote{See, for instance, Beshkar and Bond (2016), Bown and Crowley (2014), Busch and Pelc (2014), and Kuenzel (2020).} Even if we know what the applied tariffs were, we can’t know how much water is in the bindings if we don’t also know the negotiated tariff caps.

In this paper, we briefly describe the historical context of the GATT negotiations (Section \@ref(context)) as well as the sources of data on the negotiated schedules and our process of acquiring, standardizing and digitizing key tariff schedules for the United States from 1930 to 1964 that cover the Smoot-Hawley unilateral tariffs of 1930 through the fifth round of the GATT (Section \@ref(data)). We are in the process of adding the remaining three rounds and creating a concordance between the nomenclature of the Smoot Hawley Act and the revised U.S. tariff system as of 1963.

We then provide summary statistics in Section \@ref(results) that describe the the U.S. tariff schedules and the tariff liberalization that is inherent in them. We analyze specific (i.e. per quantity) tariffs and *ad valorem* (as a percentage of value) tariff separately. We are in the process of combining *ad valorem* equivalent data with the GATT schedules so that all tariffs in order to obviate the need for this distinction.

We analyze the tariff cuts in aggregate, through time, and across types of products. We find significant heterogeneity across rounds in line with what one would expect given the varying conditions under which negotiations took place; we describe these conditions in Section \@ref(context). We also find interesting differences between the tariff levels and cuts across industrial groups by analyzing the data by Schedule, as the fifteen Schedules are the Smoot Hawley system's way of dividing products into industrial groups.

We find that the bilateral trade agreements flowing out of the Reciprocal Trade Agreements Act (RTAA) of 1934 made an important contribution to the amount of liberization that was achieved between 1930 and 1964 even before the GATT began in 1947. We also find no evidence that the United States negotiators sytematically substituted *ad valorem* tariffs for specific tariffs even though inflation had substantially reduced the protection afforded by specific tariffs since 1930. This is particularly surprising given than roughly half the items in our dataset have specific tariffs during this period. Finally, we see that negotiated tariff did increase in about 75 instances. Although this appears to be the result of rebalancing between *ad valorem* and specific at times, there are a substantial number of cases that appear to be pure increases in the bindings.