---
title: "Summary of the 02.11.15 session"
author: "Benjamin Heyries"
date: "Wednesday, February 11, 2015"
output: word_document
---

## Work done this week
  * Researched on the questions of the last session: the exact function of the TAA (it is alike fast track system); the TAA may apply in GATT as it allows the president to negotiate tariff levels; the relation between the formation of the GATT and the TAA is still unclear but a strong resemblance in their amendments points at an existing correlation between the two. For example, the introduction of the escape clause in the ITO charter in 1945 after stiff negotiations happens at the same time as the setting of an escape clause in the TAA in the extensions of 1945 and 1948.
  * Read _The GATT legal system and World Trade Diplomacy_ by Robert Hudec and started to make a summary of the book. 

## Content of the meeting
  * Shared of the precedent answers and correction of some unclear or wrong assertion of the last meeting. 
  * Questions about the book (difference between quotas and quantitative restriction, form of the summary, formalization of some rules of the game or markers like the escape clause, the ratification of the agreement or the observation of the delay of ratification).
  * Directives for the next week.

## Work for the week
  * Finish the summary of _The GATT legal system and World Trade Diplomacy_ by Robert Hudec.
  * Read _Traders and diplomats_ on the Kennedy round.
  * Start looking at the WTO data in order to find the final tariff agenda of any round. 