---
title: "Hidden Barriers to International Trade by G. and V. Curzon"
author: "K. Buzard"
date: "Monday, July 18, 2016"
output: word_document
---


Major Trade Problems: Priorities for Action
===================================================

[Note this treatise was published in 1970]

After end of Kennedy Round  and before publishing of this book/paper, lobbies were pushing (unsuccessfully) for non-tariff barriers to trade (NTB's) in the U.S. Specifically: chemicals, steel, heavy engineering, textiles, footwear.

In western Europe, they had just established common standards for electronic components that were detrimental to U.S. producers. (pg. 3)

### Gradualism

"Thus a comprehensive trade negotiation, while aiming at the elimination of tariffs and other trade barriers on industrial goods, should not attempt to abolish all of them. The more tender areas might have to wait. Certain tariffs might have to be reduced rather than eliminated; one should not attempt to negotiate agricultural commodity by agricultural commodity, but try to achieve a broad agreement on how to share the available markets. Finally, one should not try to cut through the maze of non-tariff barriers section by section. An attempt should instead be made to reach a broad agreement on respective rights and obligations or, where appropriate, to negotiate package deals and trade-ofs, leaving the residue to be eroded by time."



Ch. 2: Non-Tariff Protection: Present State of the Arts
===================================================

### Quantitative Restrictions

Originally limited to `textiles and other simple manufactures' from Japan, Hong Kong and Korea, voluntary restrictions have been extended to other products such as steel and electronics.

### Quantitative Restrictions

Shipbuilding is heavily protected in the U.S. by the 1936 Merchant Marine Act, which requires the U.S. fleet be built and maintained by U.S. shipbuilders. Japan, on the other hand, subsidizes exports.

### Customs Valuation

The `American Selling Price' (ASP) is 'the most notorious non-tariff barrier of all.' Covers only 1 percent of total U.S. imports. Started with benzenoid chemicals in the 1920s to provide protection against recovering German firms. By Kennedy round, also covered pharmaceuticals, rubber footwear, canned clams, knitted wool gloves and mittens, chocolate and sugar confectionary and various machinery and machinery tools.

ASP takes the higher U.S. price as the basis for duty calculations, not the foreign invoice price. Since it's usually the manufacturer's list price that is used, all the domestic firm has to do to get more protection is to raise its list price (at which very little product is actually sold; most is discounted).

Abolition of ASP was negotiated in Kennedy round, but required Congressional approval that was not yet forthcoming when the book was written.

### Discriminatory Excise Taxes

The way the U.S. taxes alcohol discriminates against Scotch whisky. It was unsuccessfully negotiated in the Kennedy round and then brought to the U.S. courts under the Anglo-American Convention on Commerce (1815) and the US-Irish Treat of Friendship, Commerce and Navigation (1950).