---
title: "Tariffs concession of the USA to Australia"
author: "Benjamin Heyries"
date: "Saturday, February 21, 2015"
output: html_document
---

This is a document that display the concessions made by the United States to Australia during the different round of the GATT. The list is not exhaustive as only relevant item are put into the table. The list of excluded item can be found at the end of the document.
The tariffs concessions are displayed by round.

The Geneva I round
================

```{r}
tariffs <- matrix(c(8220350, 50, 8220370, 50, 8220390, 50, 8130900, 50, 8380950,50, 8140590, 25, 8130880, 50, 2345900, 50, 2290200, 50, 4209800, 50, 4225000, 50, 0018000, 50, 0019000, 50, 0815600, 8.3, 0021000, 50, 0022000, 50, 0023500, 50, 0023600, 50, 0044000, 50, 1330890, 50, 2410070, 50, 2410100, 50, 2410200, 50, 2410500, 50, 1197000, 60, 3520000, 25, 3521000, 25, 3521100, 25, 3521200, 25, 3521300, 25, 3522000, 25, 3523000, 25, 3523100, 25, 3523200, 25, 3523300, 25, 3526000, 25, 3527000, 25, 3527100, 25, 3527200, 25, 3527300, 25, 3528000, 25, 3529000, 25, 3529100, 25, 3529200, 25, 3529300, 25, 3541000, 37.5, 0734500, 20, 0734520, 37.5, 0751400, 0, 0751420, 45, 0759900, 50, 0207000, 0, 0208000, 0, 0990130, 50, 5954300, 0, 5954580, 0, 5954590, 0, 0231300, 0, 0703000, 0, 0719000, 0, 0729500, 0, 6270400, 0, 6270500, 0, 0961000, 0, 0962500, 0, 0034000, 0, 0035500, 0, 0979300, 0, 0231500, 0, 0231700, 0, 0234000, 0, 0235500, 0, 0291000, 0, 4033800, 0), ncol=2, byrow=TRUE)
colnames(tariffs) <- c("Code 1946", "Percentage concession 1946")

tariffscode <- matrix(c("2.5 ct per lb", "Tannic acid", "5.5 ct/lb", "Tannic acid", "9 ct/lb", "Tannic acid", "12.5 %", "Medical preparations", "12.5 %", "Chimical product: Eucalyptol", "12.5%", "Prepration in pills: Eucalyptol", "17.5%", "Thymol from eucalyptus", "7.5%", "Taning extracts", "7.5%", "Essential oil of E", "10%", "Veneers" , "16.33% and 10%", "Tennis racket frame", "3 ct per lb", "Beef", "3 ct per lb", "Veal", "0", "Beef and mutton tallow", "2.5 ct per lb", "Mutton", "3.5 ct per lb", "Lamb", "3 ct per lb", "Game", "1.5 ct/lb, 7.5% min", "Edible offal", "1.5 ct per lb or min 7.5 %", "Butter", "7 ct per lb", "Other fruit paste", "1 ct per lb", "Grass and crop seeds", "1 ct per lb", "Grass and crop seeds", "0.5 ct per lb", "Grass and crop seeds", "1 ct per lb", "Grass and crop seeds", "87.5 ct per lb", "Peas", "9.5 ct/lb", "Clothing wool", "8 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "9.25 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "8 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "9.25 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "8 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "9.25 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "8 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "9.25 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "8 ct/lb", "Clothing wool", "9.5 ct/lb", "Clothing wool", "9.25 ct/lb", "Clothing wool", "9.25 ct per lb and 6.25%", "Carbonized wool", "2.5%", "Dressed fur not dyed", "7.5%", "Dyed dressed furs", "0", "Manufactured fur not dyed", "17.5%", "Manufactured fur dyed", "25%", "All other fur articles", "0", "Hides and skins",  "0", "Hides and skin", "20%", "Catgut", "Bind 0", "Precious stones", "Bind 0", "Precious stones", "Bind 0", "Precious stones", "Bind 0", "Fur and fur skins: Lamb", "Bind 0", "Fur and fur skins: Rabbit",  "Bind 0", "Fur and fur skins: opossum", "Bind 0", "Fur and fur skin: others", "Bind 0", "Tantalum ore", "Bind 0", "Zirconium", "Bind 0", "Shells: mother-of-pearl", "Bind 0", "Tortoise shell", "Bind 0", "Sausage cacinge", "Bind 0", "Sausage Cacinge", "Bind 0", "Integruments, tendons, intestine", "Bind 0", "Other sheep and lamb skin", "Bind 0", "Other sheep and lamb skin", "Bind 0", "Other sheep and lamb skin", "Bind 0", "Other sheep and lamb skin", "Bind 0", "Kangoroo skin", "Bind 0", "Oriental wood"), ncol=2, byrow=TRUE)
colnames(tariffscode) <- c("Absolute concession 1946", "Description article")
data.frame(tariffs, tariffscode)
```

The Geneva II round
================
```{r}
tariffs <- matrix(c(2345, 20, 6.6, 6.6, 6.6, 2290, 20, 6.6, 6.6, 6.6, 23500, 16.6, 6.6, 3.3, 6.6, 0990, 15, 5, 5, 5), ncol=5, byrow=TRUE)
colnames(tariffs) <- c("Code 1954", "Percentage concession 1954", "Stage 1", "X2", "X3")
tariffscode <- matrix(c("1.5%", "Tanning extract", "Yes", "1.5%", "Eucalyptus Oil", "Yes", "0.5 ct per lb", "Game", "Yes", "3%", "Catgut", "Yes"), ncol=3, byrow=TRUE)
colnames(tariffscode) <- c("Absolute concession 1954", "Description article", "Correspondance code 1946")
data.frame(tariffs, tariffscode)
```

